---
title: "ICE ERO-LESA arrests data Nov. 2023-Feb. 2025"
author: "UWCHR"
date: "2025-03-25"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl)

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Admin_Arrests.xlsx"

arrest_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(apprehension_date = as.Date(apprehension_date)) |>
  mutate(apprehension_method = fct(apprehension_method)) |>
  mutate(criminality = apprehension_criminality == "1 Convicted Criminal") |>
  mutate(n_dupe = row_number(), .by = c("apprehension_date", "apprehension_method", "apprehension_criminality", "unique_identifier")) |>
  filter(is.na(unique_identifier) | n_dupe == 1) |>
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"))

```

```{r natl_trend}

figure_1 <-
  arrest_df |>
    filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week) |>
  ggplot(aes(week, n)) +
geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  coord_cartesian(clip = "off") +
  labs(title = "Weekly arrests by Immigration and Customs Enforcement (ICE)",
       subtitle = "Nationwide",
       x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,10,0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_1

figure_2 <-
  arrest_df |>
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
  filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(criminality = factor(criminality, levels = c(TRUE, FALSE), labels = c("Criminal conviction", "No criminal conviction"))) |>
  count(criminality, week) |>
  ggplot(aes(week, n, color = criminality, group = criminality)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by Criminal Conviction Status", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_2

```


```{r sea_trend}

sea <- arrest_df %>% 
  filter(apprehension_aor == "Seattle Area of Responsibility")

figure_1 <-
  sea |>
    filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week) |>
  ggplot(aes(week, n)) +
geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  coord_cartesian(clip = "off") +
  labs(title = "Weekly arrests by Immigration and Customs Enforcement (ICE)",
       subtitle = "Seattle Area of Responsibility",
       x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,10,0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_1

figure_2 <-
  sea |>
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
    filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(criminality = factor(criminality, levels = c(TRUE, FALSE), labels = c("Criminal conviction", "No criminal conviction"))) |>
  count(criminality, week) |>
  ggplot(aes(week, n, color = criminality, group = criminality)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma, limits = c(0, 100)) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by Criminal Conviction Status (Seattle AOR)", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_2

```


```{r wa_trend}

wa <- arrest_df %>% 
  filter(apprehension_state == "WASHINGTON")

dat_1 <-
  wa |>
    filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week)

figure_1 <- dat_1 %>% 
  ggplot(aes(week, n)) +
geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  coord_cartesian(clip = "off") +
  labs(title = "Weekly arrests by Immigration and Customs Enforcement (ICE)",
       subtitle = "WA state",
       x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,10,0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_1

dat_2 <-
  wa |>
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
    filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(criminality = factor(criminality, levels = c(TRUE, FALSE), labels = c("Criminal conviction", "No criminal conviction"))) |>
  count(criminality, week)

figure_2 <- dat_2 %>% 
  ggplot(aes(week, n, color = criminality, group = criminality)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma, limits = c(0, 100)) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by Criminal Conviction Status (WA state)", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_2

write_delim(dat_1, here::here('analyze', 'output', "wa_arrests.csv"), delim=',' )
write_delim(dat_2, here::here('analyze', 'output', "wa_arrests_crim.csv"), delim=',')

```


```{r pre_post_trump_change_method}

dat <- arrest_df %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
         trump = apprehension_date >= "2025-01-20") %>% 
  group_by(trump, week, apprehension_method) %>% 
  count() %>% 
  group_by(trump, apprehension_method) %>% 
  summarize(weekly_mean_arrests = mean(n))

p1 <- dat %>% 
  ggplot(aes(x = weekly_mean_arrests, y = apprehension_method, fill = trump)) +
  geom_col(position='dodge')

p1

dat2 <- dat %>% 
  pivot_wider(id_cols='apprehension_method', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_arrests') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

p2 <- dat2 %>% 
  mutate(apprehension_method = fct_reorder(apprehension_method, pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = apprehension_method, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. arrests in first months of Trump II")

p2

```

```{r pre_post_trump_change_method_2}

dat1 <- arrest_df %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
         trump = apprehension_date >= "2025-01-20") %>% 
  group_by(trump, week, apprehension_method) %>% 
  count() %>% 
  group_by(trump, apprehension_method) %>% 
  summarize(weekly_mean_arrests = mean(n)) %>% 
  pivot_wider(id_cols='apprehension_method', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_arrests') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change)) %>% 
  mutate(type = "natl")

dat2 <- arrest_df %>% 
  filter(apprehension_aor == "Seattle Area of Responsibility") %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
         trump = apprehension_date >= "2025-01-20") %>% 
  group_by(trump, week, apprehension_method) %>% 
  count() %>% 
  group_by(trump, apprehension_method) %>% 
  summarize(weekly_mean_arrests = mean(n)) %>% 
  pivot_wider(id_cols='apprehension_method', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_arrests') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change)) %>% 
  mutate(type = "sea")
  
dat <- rbind(dat1, dat2)

p1 <- dat %>% 
  mutate(apprehension_method = fct_reorder(apprehension_method, pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = apprehension_method, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. arrests in first months of Trump II") +
  facet_wrap(~type)

p1

```

```{r pre_post_trump_change_final_program}

dat <- arrest_df %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
         trump = apprehension_date >= "2025-01-20") %>% 
  group_by(trump, week, final_program) %>% 
  count() %>% 
  group_by(trump, final_program) %>% 
  summarize(weekly_mean_arrests = mean(n))

p1 <- dat %>% 
  ggplot(aes(x = weekly_mean_arrests, y = final_program, fill = trump)) +
  geom_col(position='dodge')

p1

dat2 <- dat %>% 
  pivot_wider(id_cols='final_program', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_arrests') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

p2 <- dat2 %>% 
  filter(!is.na(pct_change)) %>% 
  mutate(final_program = fct_reorder(final_program, pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = final_program, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. arrests in first months of Trump II")

p2

```

```{r det}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Detentions.xlsx"

detention_df1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>%
	janitor::clean_names()

detention_df2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>%
	janitor::clean_names()

names_1 <- names(detention_df1)
names_2 <- names(detention_df2)

stopifnot(names_1 == names_2)

detention_df <- rbind(detention_df1, detention_df2)

rm(detention_df1, detention_df2)

detention_df <- detention_df %>% 
  mutate(stay_book_in_date_time = ymd_hms(stay_book_in_date_time),
         book_in_date_time = ymd_hms(book_in_date_time),
         detention_book_out_date_time = ymd_hms(detention_book_out_date_time),
         stay_book_out_date_time = ymd_hms(stay_book_out_date_time),
         stay_book_out_date = ymd(stay_book_out_date),
         book_in_fy = substr(quarter(book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4),
         stay_book_in_fy = substr(quarter(stay_book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4)) %>% filter(!is.na(unique_identifier))


detention_df <- detention_df %>% 
  group_by(unique_identifier) %>% 
  arrange(stay_book_in_date_time, book_in_date_time, unique_identifier) %>% 
  ungroup()

detention_ids <- unique(detention_df$unique_identifier)

```

```{r arrest_by_detention_status}

arrest_df <- arrest_df %>% 
  mutate(id_in_det = unique_identifier %in% detention_ids)

figure_1 <-
  arrest_df |>
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(id_in_det = factor(id_in_det, levels = c(TRUE, FALSE), labels = c("arrest with detention", "arrest with no detention"))) |>
  count(id_in_det, week) |>
  ggplot(aes(week, n, color = id_in_det, group = id_in_det)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 6000, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by whether associated with detention", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_1

figure_2 <-
  arrest_df |>
  filter(apprehension_aor == "Seattle Area of Responsibility") %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(id_in_det = factor(id_in_det, levels = c(TRUE, FALSE), labels = c("arrest with detention", "arrest with no detention"))) |>
  count(id_in_det, week) |>
  ggplot(aes(week, n, color = id_in_det, group = id_in_det)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by whether associated with detention (SEA AOR)", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12))

figure_2

```

```{r arrest_by_crim_convict_and_det_status}

dat_natl <-
  arrest_df |>
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(id_in_det = factor(id_in_det, levels = c(TRUE, FALSE), labels = c("arrest with detention", "arrest with no detention")),
         criminality = factor(criminality, levels = c(TRUE, FALSE), labels = c("Criminal conviction", "No criminal conviction"))) |>
  count(id_in_det, criminality, week)

figure_1 <- dat_natl |>
  ggplot(aes(week, n, color = id_in_det, group = id_in_det)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by whether associated with detention (national)", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12)) +
  facet_wrap(~criminality)

figure_1

dat_sea <-
  arrest_df |>
  filter(apprehension_aor == "Seattle Area of Responsibility") %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(id_in_det = factor(id_in_det, levels = c(TRUE, FALSE), labels = c("arrest with detention", "arrest with no detention")),
         criminality = factor(criminality, levels = c(TRUE, FALSE), labels = c("Criminal conviction", "No criminal conviction"))) |>
  count(id_in_det, criminality, week)

figure_2 <- dat_sea |>
  ggplot(aes(week, n, color = id_in_det, group = id_in_det)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by whether associated with detention (SEA AOR)", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12)) +
  facet_wrap(~criminality)

figure_2

write_delim(dat_sea, here::here('analyze', 'output', 'sea_arrests_by_crim_convict_and_det_status.csv'), delim = ',')

dat_wa <-
  arrest_df |>
  filter(apprehension_state == "WASHINGTON") %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  mutate(id_in_det = factor(id_in_det, levels = c(TRUE, FALSE), labels = c("arrest with detention", "arrest with no detention")),
         criminality = factor(criminality, levels = c(TRUE, FALSE), labels = c("Criminal conviction", "No criminal conviction"))) |>
  count(id_in_det, criminality, week)

figure_3 <- dat_wa |>
  ggplot(aes(week, n, color = id_in_det, group = id_in_det)) +
  geom_vline(data = NULL, xintercept = as.Date("2025-01-20"), color = gray(0.2), linetype = "dashed") +
  annotate("text", x = as.Date("2025-01-20") - days(7), y = 100, label = "Trump II\ninauguration", hjust = 1, size = 3.5, color = gray(0.2)) +
  geom_line(linewidth = 0.8) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  coord_cartesian(clip = "off") +
  labs(color = "", title = "Weekly arrests by Immigration and Customs Enforcement (ICE)", subtitle = "by whether associated with detention (Washington state)", x = "", y = "Number of arrests per Week", caption = "Source: ICE via FOIA request") +
  theme_minimal() +
  theme(plot.margin = margin(5, 0, 5, 5),
        plot.title = element_text(margin = margin(0,0,5,0)),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0)),
        axis.title.x = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = "bottom",
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        strip.text = element_text(hjust = 0, size = 12)) +
  facet_wrap(~criminality)

figure_3

write_delim(dat_wa, here::here('analyze', 'output', 'wa_arrests_by_crim_convict_and_det_status.csv'), delim = ',')


```

```{r arrest_method}

top_methods <- arrest_df %>% 
  count(apprehension_method) %>% 
  arrange(desc(n))

p1 <- arrest_df %>% 
   mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
          apprehension_method = case_when(apprehension_method %in% head(top_methods$apprehension_method, 10) ~ apprehension_method,
                                          TRUE ~ "All others"),
          apprehension_aor = str_replace(apprehension_aor, " Area of Responsibility", "")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week, apprehension_aor, apprehension_method) %>% 
  ggplot(aes(x = week, y = n, color = apprehension_method)) +
  geom_line() +
  facet_wrap(~apprehension_aor)
  
plotly::ggplotly(p1)  

p2 <- arrest_df %>% 
  filter(apprehension_aor == "Seattle Area of Responsibility") %>% 
   mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
          apprehension_aor = str_replace(apprehension_aor, " Area of Responsibility", "")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week, apprehension_aor, apprehension_method) %>% 
  ggplot(aes(x = week, y = n, color = apprehension_method)) +
  geom_line()
  
plotly::ggplotly(p2)  

```

```{r arrest_final_program_aor}


p1 <- arrest_df %>% 
   mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
          apprehension_aor = str_replace(apprehension_aor, " Area of Responsibility", "")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week, apprehension_aor, final_program) %>% 
  ggplot(aes(x = week, y = n, color = final_program)) +
  geom_line() +
  facet_wrap(~apprehension_aor)
  
plotly::ggplotly(p1)  

```

```{r apprehension_method_detention_status}

p1 <- arrest_df %>% 
   mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
          apprehension_method = case_when(apprehension_method %in% head(top_methods$apprehension_method, 10) ~ apprehension_method,
                                          TRUE ~ "All others"),
          apprehension_aor = str_replace(apprehension_aor, " Area of Responsibility", "")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week, id_in_det, apprehension_method) %>% 
  ggplot(aes(x = week, y = n, color = id_in_det)) +
  geom_line() +
  facet_wrap(~apprehension_method)
  
plotly::ggplotly(p1)  

```

```{r misc}

p1 <- arrest_df %>% 
   mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
          apprehension_aor = str_replace(apprehension_aor, " Area of Responsibility", "")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week, id_in_det, final_program) %>% 
  ggplot(aes(x = week, y = n, color = id_in_det)) +
  geom_line() +
  facet_wrap(~final_program)
  
plotly::ggplotly(p1)

p2 <- arrest_df %>% 
  filter(final_program == "Non-Detained Docket Control") %>% 
   mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
          apprehension_aor = str_replace(apprehension_aor, " Area of Responsibility", "")) |>
      filter(week > "2023-08-28",
         week < "2025-06-09") |>
  count(week, id_in_det, final_program) %>% 
  ggplot(aes(x = week, y = n, color = id_in_det)) +
  geom_line()
  
p2

```

