---
title: "Analysis of case category status"
author: "UWCHR"
date: "2025-07-02"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, ggforce, plotly, gghighlight, viridis, readxl, ggVennDiagram)

```

Note arrests includes only ICE arrests.

```{r setup_arrests, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Admin_Arrests_LESA-STU_FINAL_unprotected.xlsx"

arrest_df<- read_excel(here('analyze', 'input', file), skip=5) %>% 
  janitor::clean_names()

arrest_df <- arrest_df %>% 
  mutate(apprehension_date = as.Date(apprehension_date)) |>
  # mutate(apprehension_method = fct(apprehension_method)) |>
  mutate(criminality = apprehension_criminality == "1 Convicted Criminal") |>
  mutate(n_dupe = row_number(), .by = c("unique_identifier")) |>
  filter(!is.na(unique_identifier))

arrest_ids <- unique(arrest_df$unique_identifier)

latest_arrest <- arrest_df %>% 
  arrange(desc(apprehension_date)) %>% 
  distinct(unique_identifier, .keep_all = TRUE)

```

Note removals includes ICE arrests and CBP apprehensions.

```{r setup_removals, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Removals_LESA-STU_FINAL_2025only_unprotected.xlsx"

removals_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(n_dupe = row_number(), .by = c("unique_identifier")) %>% 
  filter(!is.na(unique_identifier))

removal_ids <- unique(removals_df$unique_identifier)

removal_statuses <- unique(removals_df$case_status)

```

```{r plot_id_time}

arrests_2025 <- latest_arrest %>% 
  filter(departed_date >= "2025-01-01",
         !is.na(departed_date))

removal_ids <- unique(removals_df$unique_identifier)
arrest_ids <- unique(arrests_2025$unique_identifier)

sets <- list("arrests" = arrest_ids,
             "removals" = removal_ids)

vd1 <- ggVennDiagram(x = sets,
              force_upset = TRUE, order.set.by = "name", order.intersect.by = "size"
              )

vd1 

```

```{r}

# Essentially all arrests with a status indicating removal have a departed date, departure country
arrests_with_removal <- arrest_df %>% 
  filter(case_status %in% removal_statuses)

# ...and vice versa. So can use any of these vars to identify removals within arrests data
# OJO! Arrests here are only ICE arrests; versus BP arrests included in removals data
arrests_without_removal <- arrest_df %>% 
  filter(!case_status %in% removal_statuses)

```

```{r}

top_case_category_arrest <- arrest_df %>% 
  count(case_category) %>% 
  arrange(desc(n))

dat <- latest_arrest %>% 
  filter(case_status %in% removal_statuses) %>% 
  mutate(month = floor_date(departed_date, "month"),
         case_category = case_when(case_category %in% head(top_case_category_arrest$case_category) ~ case_category,
                                   TRUE ~ "All others")) %>% 
  count(month, case_category)
  
p1 <- dat %>% 
  filter(month >= "2023-10-01",
         month < "2025-05-01") %>% 
  ggplot(aes(x = month, y = n, color = case_category)) +
  geom_line() +
  labs(title = "Arrests with removal data")

plotly::ggplotly(p1)

```

```{r}

top_case_category <- removals_df %>% 
  count(case_category) %>% 
  arrange(desc(n))

dat <- removals_df %>% 
  # filter(final_program_code != "BP") %>% 
  mutate(month = floor_date(departed_date, "month"),
         case_category = case_when(case_category %in% head(top_case_category$case_category) ~ case_category,
                                   TRUE ~ "All others")) %>% 
  count(month, case_category)
  
p1 <- dat %>% 
  filter(month >= "2023-11-01",
         month < "2025-05-01") %>% 
  ggplot(aes(x = month, y = n, color = case_category)) +
  geom_line() +
  labs(title = "Removals data")

plotly::ggplotly(p1)

```



```{r}

sea_top_categories <- removals_df %>% 
  filter(docket_aor == "Seattle Area of Responsibility") %>% 
  count(case_category) %>% 
  arrange(desc(n))

dat <- removals_df %>% 
  filter(docket_aor == "Seattle Area of Responsibility") %>% 
  mutate(month = floor_date(departed_date, "month"),
         case_category = case_when(case_category %in% head(sea_top_categories$case_category) ~ case_category,
                                   TRUE ~ "All others")) %>% 
  count(month, case_category)
  
p1 <- dat %>% 
  filter(month >= "2023-11-01",
         month < "2025-05-01") %>% 
  ggplot(aes(x = month, y = n, color = case_category)) +
  geom_line()

plotly::ggplotly(p1)

```


```{r}

pending <- c('2A', '2B', '8A', '8B', '8D')
benefit <- c('5C', '5D')
expedited_admin_rein <- c('8F', '8G', '8H', '8I', '11', '16')

dat <- removals_df %>% 
  mutate(month = floor_date(departed_date, "month"),
         docket_aor = str_replace(docket_aor, " Area of Responsibility", ""),
         case_category_group = case_when(str_detect(case_category, paste0(pending, collapse="|")) ~ "pending case",
                                         str_detect(case_category, paste0(benefit, collapse="|")) ~ "benefit blocking deport",
                                         str_detect(case_category, paste0(expedited_admin_rein, collapse="|")) ~ "lack of due process",
                                         TRUE ~ "all other categories"
                                         )) %>% 
  count(month, docket_aor, case_category_group) %>% 
  group_by(month, docket_aor) %>% 
  mutate(pct = n / sum(n))
  
p1 <- dat %>% 
  filter(month >= "2023-11-01",
         month < "2025-06-01") %>% 
  ggplot(aes(x = month, y = pct, fill = case_category_group)) +
  geom_col() +
  facet_wrap(~docket_aor)

plotly::ggplotly(p1)

```

```{r}

pending <- c('2A', '2B', '8A', '8B', '8D')
benefit <- c('5C', '5D')
expedited_admin_rein <- c('8F', '8G', '8H', '8I', '11', '16')

dat_natl <- removals_df %>% 
  mutate(month = floor_date(departed_date, "month"),
         docket_aor = str_replace(docket_aor, " Area of Responsibility", ""),
         case_category_group = case_when(str_detect(case_category, paste0(pending, collapse="|")) ~ "pending case",
                                         str_detect(case_category, paste0(benefit, collapse="|")) ~ "benefit blocking deport",
                                         str_detect(case_category, paste0(expedited_admin_rein, collapse="|")) ~ "lack of due process",
                                         TRUE ~ "all other categories"
                                         )) %>% 
  count(month, case_category_group) %>% 
  group_by(month) %>% 
  mutate(pct = n / sum(n),
         type = "natl")

dat_sea <- removals_df %>% 
  filter(docket_aor == "Seattle Area of Responsibility") %>% 
  mutate(month = floor_date(departed_date, "month"),
         case_category_group = case_when(str_detect(case_category, paste0(pending, collapse="|")) ~ "pending case",
                                         str_detect(case_category, paste0(benefit, collapse="|")) ~ "benefit blocking deport",
                                         str_detect(case_category, paste0(expedited_admin_rein, collapse="|")) ~ "lack of due process",
                                         TRUE ~ "all other categories"
                                         )) %>% 
  count(month, case_category_group) %>% 
  group_by(month) %>% 
  mutate(pct = n / sum(n),
         type = "sea")

dat <- rbind(dat_natl, dat_sea)
  
p1 <- dat %>% 
  filter(month >= "2023-11-01",
         month < "2025-06-01") %>% 
  ggplot(aes(x = month, y = pct, fill = case_category_group)) +
  geom_col() +
  facet_wrap(~type)

plotly::ggplotly(p1)

```



```{r}

pending <- c('2A', '2B', '8A', '8B', '8D')
benefit <- c('5C', '5D')
expedited_admin_rein <- c('8F', '8G', '8H', '8I', '11', '16')

dat_natl <- arrest_df %>% 
  mutate(month = floor_date(departed_date, "month"),
         case_category_group = case_when(str_detect(case_category, paste0(pending, collapse="|")) ~ "pending case",
                                         str_detect(case_category, paste0(benefit, collapse="|")) ~ "benefit blocking deport",
                                         str_detect(case_category, paste0(expedited_admin_rein, collapse="|")) ~ "lack of due process",
                                         TRUE ~ "all other categories"
                                         )) %>% 
  count(month, case_category_group) %>% 
  group_by(month) %>% 
  mutate(pct = n / sum(n),
         type = "natl")

dat_sea <- arrest_df %>% 
  filter(apprehension_aor == "Seattle Area of Responsibility") %>% 
  mutate(month = floor_date(departed_date, "month"),
         case_category_group = case_when(str_detect(case_category, paste0(pending, collapse="|")) ~ "pending case",
                                         str_detect(case_category, paste0(benefit, collapse="|")) ~ "benefit blocking deport",
                                         str_detect(case_category, paste0(expedited_admin_rein, collapse="|")) ~ "lack of due process",
                                         TRUE ~ "all other categories"
                                         )) %>% 
  count(month, case_category_group) %>% 
  group_by(month) %>% 
  mutate(pct = n / sum(n),
         type = "sea")

dat <- rbind(dat_natl, dat_sea)
  
p1 <- dat %>% 
  filter(month >= "2023-11-01",
         month < "2025-06-01") %>% 
  ggplot(aes(x = month, y = pct, fill = case_category_group)) +
  geom_col() +
  facet_wrap(~type, scales = "free_y")

plotly::ggplotly(p1)


```

```{r}

arrests_subset <- arrest_df %>% 
  dplyr::select(unique_identifier, case_status, case_category, n_dupe)

removals_subset <- removals_df %>% 
  dplyr::select(unique_identifier, case_status, case_category, n_dupe)

compare_subsets <- inner_join(arrests_subset, removals_subset, by="unique_identifier", suffix = c(".arrests", ".removals"), relationship = "many-to-many")

compare_subsets$status_equal <- compare_subsets$case_status.arrests == compare_subsets$case_status.removals

compare_subsets$category_equal <- compare_subsets$case_category.arrests == compare_subsets$case_category.removals

unequal_compare <- compare_subsets %>% 
  filter(status_equal != TRUE | category_equal != TRUE)

unequal_status <- compare_subsets %>% 
  filter(status_equal != TRUE)

unequal_category <- compare_subsets %>% 
  filter(category_equal != TRUE)

```


