---
title: "Comparison of anonymized identifiers across datasets"
author: "UWCHR"
date: "2025-03-31"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, ggVennDiagram, UpSetR)

```


```{r setup_encounters, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Encounters_FINAL_unprotected.xlsx"

encounter_df_1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>%
  janitor::clean_names() %>%
  mutate(event_date = as.Date(event_date))

encounter_df_2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>%
  janitor::clean_names() %>%
  mutate(event_date = as.Date(event_date))

encounter_df <- rbind(encounter_df_1, encounter_df_2)

rm(encounter_df_1, encounter_df_2)

```


```{r setup_detainers}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Detainers_LESA-STU_FINAL_unprotected.xlsx"

detainer_df<- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

detainer_df<- detainer_df%>% 
  mutate(date_diff = difftime(detainer_prepare_date, apprehension_date, units = "days"))

detainer_ids <- unique(detainer_df$unique_identifier)

```

```{r setup_arrests, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Admin_Arrests_LESA-STU_FINAL_unprotected.xlsx"

arrest_df<- read_excel(here('analyze', 'input', file), skip=5) %>% 
  janitor::clean_names()

arrest_df <- arrest_df %>% 
  mutate(apprehension_date = as.Date(apprehension_date)) |>
  mutate(apprehension_method = fct(apprehension_method)) |>
  mutate(criminality = apprehension_criminality == "1 Convicted Criminal") |>
  mutate(n_dupe = row_number(), .by = c("unique_identifier"))

```

```{r setup_detention, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Detentions_LESA-STU_FINAL_unprotected.xlsx"

df1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>%
	janitor::clean_names() %>% 
	mutate(stay_book_in_date_time = ymd_hms(stay_book_in_date_time),
	         book_in_date_time = ymd_hms(book_in_date_time),
	         detention_book_out_date_time = ymd_hms(detention_book_out_date_time),
	         stay_book_out_date_time = ymd_hms(stay_book_out_date_time),
	         stay_book_out_date = ymd(stay_book_out_date))

df2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>%
	janitor::clean_names() %>% 
	mutate(stay_book_in_date_time = ymd_hms(stay_book_in_date_time),
	         book_in_date_time = ymd_hms(book_in_date_time),
	         detention_book_out_date_time = ymd_hms(detention_book_out_date_time),
	         stay_book_out_date_time = ymd_hms(stay_book_out_date_time),
	         stay_book_out_date = ymd(stay_book_out_date))

names_1 <- names(df1)
names_2 <- names(df2)

stopifnot(names_1 == names_2)

detention_df <- rbind(df1, df2)

rm(df1, df2)

```

```{r setup_removals, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Removals_LESA-STU_FINAL_2025only_unprotected.xlsx"

removals_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

removal_ids <- unique(removals_df$unique_identifier)

```

```{r compare_sets}

data_levels <- c("encounter", "detainer", "arrest", "detention", "removal")

sets <- list("encounter" = encounter_ids,
             "detainer" = detainer_ids,
             "arrest" = arrest_ids,
             "detention" = detention_ids,
             "removal" = removal_ids)

# p1 <- ggVennDiagram(x = sets,
#                     color = name,
#                     label = "count") +
#   scale_fill_gradient(low = "#F4FAFE", high = "#4981BF")
# 
# p1

p2 <- ggVennDiagram(x = sets,
              force_upset = TRUE, order.set.by = "name", order.intersect.by = "size"
              )

p2 

```


Missingness of `unique_identifier` within and across datasets.

```{r compare_missingness_id}

dat1 <- encounter_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "encounter")

dat2 <- detainer_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "detainer")

dat3 <- arrest_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "arrest")

dat4 <- detention_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "detention")

dat5 <- removals_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "removal")

dat <- rbind(dat1, dat2, dat3, dat4, dat5)

p1 <- dat %>% 
  mutate(type = factor(type, levels = data_levels)) %>% 
  ggplot(aes(x = type, y = n, fill = missing_id)) +
  geom_col()

p1

p1.1 <- dat %>% 
  mutate(type = factor(type, levels = data_levels)) %>% 
  ggplot(aes(x = type, y = n, fill = missing_id)) +
  geom_col(position="fill")

p1.1

```

