---
title: "ICE ERO-LESA detention data Nov. 2023-Feb. 2025"
author: "UWCHR"
date: "2025-03-25"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, digest)

file_old <- "headcount_detloc_nov23-jul25.csv.gz"

df_old <- read_delim(here('analyze', 'input', file_old), delim='|') %>% 
  mutate(date = as.Date(date))

file_new <- "headcount_detloc_nov23-oct25.csv.gz"

df <- read_delim(here('analyze', 'input', file_new), delim='|') %>% 
  mutate(date = as.Date(date))

```

```{r known_facilities}

known_facil <- read_delim(here::here('analyze', 'input', 'facilities.csv.gz'), delim ='|')

df <- df %>% 
  mutate(known_facil = detention_facility_code %in% unique(known_facil$detloc),
         trump = date >= "2025-01-20")

to_join <- known_facil %>% 
  dplyr::select(detloc, aor, state) %>% 
  rename(detention_facility_code = detloc,
         detention_facility_aor = aor,
         detention_facility_state = state)

df <- df %>% 
  left_join(to_join, by="detention_facility_code")

df <- df %>% 
  mutate(detention_facility_region = case_when(
          detention_facility_aor == "ATL" ~ "Interior/Northern",
          detention_facility_aor == "BAL" ~ "Interior/Northern",
          detention_facility_aor == "BOS" ~ "Interior/Northern",
          detention_facility_aor == "BUF" ~ "Interior/Northern",
          detention_facility_aor == "CHI" ~ "Interior/Northern",
          detention_facility_aor == "DAL" ~ "Interior/Northern",
          detention_facility_aor == "DEN" ~ "Interior/Northern",
          detention_facility_aor == "DET" ~ "Interior/Northern",
          detention_facility_aor == "ELP" ~ "Southern",
          detention_facility_aor == "HOU" ~ "Southern",
          detention_facility_aor == "LOS" ~ "Interior/Northern",
          detention_facility_aor == "MIA" ~ "Interior/Northern",
          detention_facility_aor == "NEW" ~ "Interior/Northern",
          detention_facility_aor == "NOL" ~ "Interior/Northern",
          detention_facility_aor == "NYC" ~ "Interior/Northern",
          detention_facility_aor == "PHI" ~ "Interior/Northern",
          detention_facility_aor == "PHO" ~ "Southern",
          detention_facility_aor == "SEA" ~ "Interior/Northern",
          detention_facility_aor == "SFR" ~ "Interior/Northern",
          detention_facility_aor == "SLC" ~ "Interior/Northern",
          detention_facility_aor == "SNA" ~ "Southern",
          detention_facility_aor == "SND" ~ "Southern",
          detention_facility_aor == "SPM" ~ "Interior/Northern",
          detention_facility_aor == "WAS" ~ "Interior/Northern"))

```

```{r}

p1 <- df %>% 
  filter(date > "2024-01-01") %>% 
  group_by(date) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n)) +
  geom_line() +
  geom_vline(xintercept=as.Date("2025-01-20"), linetype="dashed") +
  ylim(0,NA)

p1

```

```{r}

p1 <- df %>% 
  filter(date > "2024-01-01") %>% 
  group_by(date, known_facil) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n, color = known_facil)) +
  geom_line()

plotly::ggplotly(p1)

```

```{r}

p1 <- df %>% 
  filter(date > "2024-01-01") %>% 
  group_by(date, detention_facility_aor) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n, color = detention_facility_aor)) +
  geom_line()

plotly::ggplotly(p1)

```

```{r}

p1 <- df %>% 
  filter(date > "2024-01-01") %>% 
  group_by(date, detention_facility_state) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n, color = detention_facility_state)) +
  geom_line()

p1

```

```{r}

p1 <- df %>% 
  filter(date > "2024-01-01") %>% 
  group_by(date, detention_facility_region) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n, color = detention_facility_region)) +
  geom_line() +
  geom_vline(xintercept=as.Date("2025-01-20"), linetype="dashed") +
  ylim(0,NA)

p1

```

# Pct change

```{r}

dat <- df %>% 
  filter(date > "2024-11-01") %>% 
  group_by(date, trump, detention_facility_aor) %>% 
  summarize(n = sum(n)) %>% 
  group_by(trump, detention_facility_aor) %>% 
  summarize(adp = mean(n))

dat2 <- dat %>% 
  pivot_wider(id_cols='detention_facility_aor', names_from = "trump", names_prefix="trump_", values_from= 'adp') %>% 
  mutate(diff = trump_TRUE - trump_FALSE,
          pct_change = ((diff) / trump_FALSE) * 100,
         ) %>% 
  arrange(desc(pct_change))

p1 <- dat %>% 
  ggplot(aes(y = detention_facility_aor, x = adp, fill = trump)) +
  geom_col(position = "dodge")

p1

p2 <- dat2 %>% 
  mutate(detention_facility_aor = fct_reorder(detention_facility_aor, diff),
         pos = diff > 0) %>% 
  ggplot(aes(x = diff, y = detention_facility_aor, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Change ADP, last 2 months of Biden versus first weeks of Trump II")

p2

p2.1 <- dat2 %>% 
  mutate(detention_facility_aor = fct_reorder(detention_facility_aor, pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = detention_facility_aor, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change ADP, last 2 months of Biden versus first weeks of Trump II")

p2.1

```

```{r old_headcount}

old_headcount <- read_delim(here::here('analyze', 'input', 'headcount_fy12-24ytd.csv.gz')) %>% 
  mutate(dataset = "UWCHR") %>% 
  filter(date >= "2011-11-01")

new_headcount <- df %>% 
  filter(date >= "2023-11-15") %>%
  dplyr::select(date, n, detention_facility_code) %>% 
  mutate(dataset = "Deportation Data Project")

dat <- rbind(old_headcount, new_headcount)

p1 <- dat %>% 
  group_by(dataset, date) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n, color = dataset)) +
  geom_line() +
  ylim(0, NA) +
  labs(title = "National ICE detention population, Nov. 2011 - Oct. 2025",
       subtitle = "Comparison of UWCHR, Deportation Data Project datasets")

p1

p2 <- dat %>% 
  filter(date >= "2023-06-01" & date <= "2024-06-30") %>% 
  group_by(dataset, date) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n, color = dataset)) +
  geom_line() +
  ylim(0, NA) +
  labs(title = "National ICE detention population, Jun. 2023 - June 2024",
       subtitle = "Comparison of UWCHR, Deportation Data Project datasets")

p2

```

```{r headcount_diff}

# Comparing period of overlap of UWCHR, DDP national detention data; for period from Nov. 15, 2023 through Jan. 4, 2024, difference between datasets no more than near 200 for a given day.

dat_wide <- dat %>%
  pivot_wider(id_cols = c('date', 'detention_facility_code'), names_from = 'dataset', values_from = "n")

dat_wide_natl <- dat_wide %>% 
  group_by(date) %>% 
  summarize(n_uwchr = sum(UWCHR, na.rm=TRUE),
            n_ddp = sum(`Deportation Data Project`, na.rm=TRUE)) %>% 
  mutate(diff = n_uwchr - n_ddp)

p1 <- dat_wide_natl %>% 
  ggplot(aes(x = date, y = diff)) +
  geom_line()

p1

p2 <- dat_wide_natl %>% 
  filter(date >= "2023-11-15",
         date <= "2024-01-04") %>% 
  ggplot(aes(x = date, y = diff)) +
  geom_line()

p2

```

```{r old_headcount_cscnwwa}

old_headcount_cscnwwa <- old_headcount %>% 
  mutate(dataset = "UWCHR") %>% 
  filter(date >= "2011-11-01",
         detention_facility_code == "CSCNWWA")

new_headcount_cscnwwa <- df %>% 
  filter(date >= "2023-11-15",
         detention_facility_code == "CSCNWWA") %>%
  dplyr::select(date, n, detention_facility_code) %>% 
  mutate(dataset = "DDP")

dat <- rbind(old_headcount_cscnwwa, new_headcount_cscnwwa)

p1 <- dat %>% 
  group_by(dataset, date) %>% 
  summarize(n = sum(n)) %>% 
  ggplot(aes(x = date, y = n, color = dataset)) +
  geom_line() +
  geom_hline(yintercept = 1575) +
  ylim(0, NA) +
  ylab("Population") +
  labs(title = "NWIPC daily detention population",
       subtitle = "Nov. 2011 - Oct. 2025",
       caption = "Data source: ICE data obtained via FOIA")

p1

write_delim(dat, here::here("analyze", "output", "nwipc_headcount.csv"), delim=',')

p2 <- dat %>% 
  group_by(dataset, date) %>% 
  summarize(n = sum(n)) %>% 
  filter(dataset == "DDP") %>% 
  ggplot(aes(x = date, y = n, color = dataset)) +
  geom_line() +
  geom_hline(yintercept = 1575) +
  ylim(0, NA) +
  ylab("Population") +
  labs(title = "NWIPC daily detention population",
       subtitle = "Nov. 15, 2024 - Oct. 16, 2025",
       caption = "Data source: ICE data obtained via FOIA")

p2

```

```{r release_compare}

df_new <- df %>% 
  mutate(release = "2025-12") %>% 
  dplyr::select(detention_facility_code, n, date, release)

df_old <- df_old %>% 
  mutate(release = "2025-08")

dat <- rbind(df_new, df_old)

dat <- dat %>% 
  group_by(date, release) %>% 
  summarize(n = sum(n))

p1 <- dat %>% 
  filter(date >= "2023-11-01") %>% 
  ggplot(aes(x = date, y = n, color = release)) +
  geom_line()

p1

p2 <- dat %>% 
  filter(date >= "2023-11-01") %>%
  ggplot(aes(x = date, y = n, color = release)) +
  geom_line()

p2

dat_wide <- dat %>% 
  pivot_wider(id_cols = c(date), values_from = n, names_from = release, names_prefix="release_") %>% 
  mutate(diff = `release_2025-12` - `release_2025-08`)

p3 <- dat_wide %>% 
  filter(!is.na(`release_2025-08`)) %>%
  ggplot(aes(x = date, y = diff)) +
  geom_line() +
  # ylim(0, NA) +
  labs(title="New headcount minus old headcount")

p3

```

```{r}

dat <- df %>% 
  filter(detention_facility_code %in% c("WEBDCTX", "RGRNDTX", "ELVDFTX"))

p1 <- dat %>% 
  filter(date >= "2025-03-01",
         date <= "2025-04-30") %>% 
  ggplot(aes(x = date, y = n, color = detention_facility_code)) +
  geom_line() +
  ylim(0,NA)

p1

```
Major new facilities below:

From FY2026 detention stats:
ERO EL PASO CAMP EAST MONTANA	EROFCB
FLORIDA SOFT-SIDED FACILITY-SOUTH	FLDSSFS
CAL CITY ICE PROCESSING CENTER	CACTYCA
FOLKSTON D RAY ICE PROCESSING CTR	FIPCDGA
LOUISIANA ICE PROCESSING CENTER	LICEPLA

Unknown:
FLBAKCI


```{r}

aug_facil <- unique(df_old$detention_facility_code)
dec_facil <- unique(df$detention_facility_code)

new_facil <- setdiff(dec_facil, aug_facil)

dat <- df %>% 
  filter(detention_facility_code %in% new_facil)

p1 <- dat %>% 
  ggplot(aes(x = date, y = n, color = detention_facility_code)) +
  geom_line() +
  ylim(0,NA)

plotly::ggplotly(p1)

```

