---
title: "ICE ERO-LESA detention data Nov. 2023-Feb. 2025"
author: "UWCHR"
date: "2025-03-25"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, digest, ggsankeyfier)

file <- "ice_detentions_nov23-oct25.csv.gz"

df <- arrow::read_parquet("https://github.com/deportationdata/ice/raw/refs/heads/main/data/detention-stints-latest.parquet")

pnw_facil <- c("FDLHOLD",
"HAVMCWA",
"RICHOLD",
"SPOHOLD",
"STJMCWA",
"TACGHWA",
"WNTHOLD",
"ABRDNWA",
"ADAMSWA",
"BLHHOLD",
"BENTOWA",
"CHELAWA",
"CLJUVWA",
"CLARKWA",
"COWLIWA",
"COWJVWA",
"ECOLOWA",
"FERRYWA",
"FORKSWA",
"FRANKWA",
"GRANTWA",
"KINCOWA",
"KITTIWA",
"MARTIWA",
"MASONWA",
"WAMCNEI",
"CSCNWWA",
"OKANOWA",
"PENDOWA",
"RRFINWA",
"REGJCWA",
"BOPSET",
"SEAICDF",
"SEAHOLD",
"SPOKAWA",
"STEVEWA",
"SUNNYWA",
"THURSWA",
"WHICOWA",
"YIKIMWA",
"YAKHOLD",
"MEDHOLD",
"POOHOLD",
"EUGHOLD")

big_new <-
      c(
        "EROFCB", # Camp East Montana
        "EPSSFTX", # El Paso soft-sided
        "FLDSSFS", # Florida soft-sided / alligator alcatraz
        "GTMOBCU", # Guantanamo
        "GTMODCU", # Guantanamo
        "GTMOACU", # Guantanamo
        "INMIAMI", # Speedway slammer
        "NEMCCOI", # Cornhusker clink
        "LICEPLA", # Angola / camp 57
        "DHDFNJ", # Delaney Hall
        "CACTYCA", # California City Corrections  - reopened by CoreCivic in 2025
        "IRWINGA", # Irwin County - reopened by LaSalle Corrections in 2025
        "NRLKCMI", # North Lake Processing Faciliy - reopened by Geo in 2025
        "FIPCAGA", # Folkston annex - opened by Geo in 2025
        "OKCIMMC", # Cimarron - CoreCivic 2025
        "OKDBACK", # Diamondback - CoreCivic 2026
        "STFRCTX", # Dilley
        "FLBAKCI" # Baker Correctional Institution - reopened in 2025
      )

```

```{r detain_setup}

max_date <- max(df$book_in_date_time, na.rm=TRUE)

df <- df %>% 
  filter(!is.na(stay_book_in_date_time),
         !is.na(book_in_date_time)) %>% 
  mutate(stay_length = difftime(stay_book_out_date_time,
            stay_book_in_date_time, unit='days'),
         placement_length = difftime(book_out_date_time,
            book_in_date_time, unit='days'),
         stay_length_elapsed = difftime(replace_na(stay_book_out_date_time, max_date),
            stay_book_in_date_time, unit='days'),
         placement_length_elapsed = difftime(replace_na(book_out_date_time, max_date),
            book_in_date_time, unit='days'),
         initial_placement_exact = stay_book_in_date_time == book_in_date_time,
         initial_placement_approx = date(stay_book_in_date_time) == date(book_in_date_time)
         )

df <- df %>% 
  filter(!is.na(unique_identifier)) %>% 
  group_by(unique_identifier) %>% 
  arrange(stay_book_in_date_time, book_in_date_time) %>%
  mutate(total_stays = n_distinct(stay_book_in_date_time),
         total_placements = n(),
         current_stay = is.na(stay_book_out_date_time),
         current_placement = is.na(book_out_date_time),
         stay_count = data.table::rleid(stay_book_in_date_time)) %>% 
  ungroup()

df <- df %>% 
  group_by(stay_ID) %>% 
  arrange(stay_book_in_date_time, book_in_date_time) %>%
  mutate(placement_count = data.table::rleid(stint_ID),
         stay_placements = n(),
         first_facil = detention_facility_code[[1]], 
         last_facil = detention_facility_code[[length(detention_facility_code)]],
         prev_facil = lag(detention_facility_code, n=1),
         next_facil = lead(detention_facility_code, n=1),
         longest_placement_facil = detention_facility_code[which.max(placement_length_elapsed)],
         last_placement = placement_count == stay_placements,
         longest_placement = placement_length_elapsed == max(placement_length_elapsed)
         ) %>% 
  ungroup()

```

`detention_facility` == "ERO EL PASO CAMP EAST MONTANA"
`detention_facility_code` == "EROFCB"

```{r transfers_from_cscnwwa}

cscnwwa_transfers <- df %>% 
  filter(detention_facility_code == "CSCNWWA",
         detention_release_reason == "Transferred")

cscnwwa_transfer_destinations <- cscnwwa_transfers %>% 
  count(next_facil) %>% 
  arrange(desc(n))

p1 <- cscnwwa_transfers %>% 
  filter(book_out_date_time >= "2025-01-01") %>% 
  mutate(week = floor_date(book_out_date_time, "week", "Monday")) %>% 
  count(week, next_facil) %>% 
  ggplot(aes(x = week, y = n, fill = next_facil)) +
  geom_col() +
  gghighlight(next_facil == "EROFCB") +
  labs(title = "Weekly transfers from NWIPC",
         subtitle = "Transfers to ERO EL PASO CAMP EAST MONTANA highlighted")

p1

```

```{r direct_transfers_cscnwwa_to_erofcb}

# Is this correct?
erofcb_from_cscnwwa <- df %>% 
  filter(detention_facility_code == "EROFCB",
         prev_facil == "CSCNWWA") %>% 
  mutate(type = "transfer to EROFCB")

other_transfers_from_cscnwwa <- df %>% 
  filter(detention_facility_code != "EROFCB",
         prev_facil == "CSCNWWA") %>% 
  mutate(type = "all other transfers")

cscnwwa_transfers_by_type <- rbind(erofcb_from_cscnwwa, other_transfers_from_cscnwwa)

first_cscnwwa_to_erofcb <- min(erofcb_from_cscnwwa$book_out_date_time, na.rm=TRUE)

cscnwwa_top_citizenship <- df %>% 
  filter(detention_facility_code == "CSCNWWA",
    book_out_date_time >= first_cscnwwa_to_erofcb) %>%
  distinct(unique_identifier, .keep_all = TRUE) %>% 
  count(citizenship_country) %>% 
  arrange(desc(n))

dat <- cscnwwa_transfers_by_type %>% 
  mutate(citizenship_country = case_when(citizenship_country %in% head(cscnwwa_top_citizenship$citizenship_country, 10) ~ citizenship_country,
                                          TRUE ~ "ALL OTHERS")) %>% 
  count(type, citizenship_country)

p1 <- dat %>% 
  ggplot(aes(x = type, y = n, fill = citizenship_country)) +
  geom_col(position = "fill")
  
p1

# erofcb_from_cscnwwa %>% 
#   count(next_facil)
# 
# erofcb_from_cscnwwa %>% 
#   count(stay_release_reason)

p2 <- cscnwwa_transfers_by_type %>% 
  count(type, next_facil) %>% 
  ggplot(aes(x = type, y = n, fill = next_facil)) +
  geom_col(position = "fill")

ggplotly(p2)

p3 <- cscnwwa_transfers_by_type %>% 
  count(type, stay_release_reason) %>% 
  ggplot(aes(x = type, y = n, fill = stay_release_reason)) +
  geom_col(position = "fill")

ggplotly(p3)

```

```{r}

p3 <- cscnwwa_transfers_by_type %>% 
  count(type, departure_country) %>% 
  ggplot(aes(x = type, y = n, fill = departure_country)) +
  geom_col(position = "fill")

ggplotly(p3)

erofcb_from_cscnwwa %>% 
  count(detention_release_reason,departure_country)


```

```{r}

cscnwwa_detentions <- df %>% 
  filter(detention_facility_code == "CSCNWWA") %>% 
  distinct(unique_identifier)

erofcb_detentions <- df %>% 
  filter(detention_facility_code == "EROFCB") %>% 
  distinct(unique_identifier)

df <- df %>% 
  mutate(cscnwwa_detention = unique_identifier %in% unlist(cscnwwa_detentions),
         erofcb_detention = unique_identifier %in% unlist(erofcb_detentions))

cscnwwa_and_erofcb <- df %>% 
  filter(cscnwwa_detention == TRUE & erofcb_detention == TRUE,
         book_in_date_time >= "2025-01-01")

```

```{r}

pnw_detentions <- df %>% 
  filter(first_facil %in% pnw_facil)

dat <- pnw_detentions %>% 
  filter(detention_facility_code %in% big_new)

length(unique(dat$unique_identifier))

poo_detentions <- df %>% 
  filter(first_facil == "POOHOLD")

dat <- poo_detentions %>% 
  filter(detention_facility_code %in% big_new)

length(unique(dat$unique_identifier))

poo_detentions_distinct <- df %>% 
  filter(first_facil == "POOHOLD") %>% 
  distinct(unique_identifier, .keep_all = TRUE)

```