---
title: "ICE ERO-LESA detention data Nov. 2023-Feb. 2025"
author: "UWCHR"
date: "2025-03-25"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, digest, ggsankeyfier, ggVennDiagram)

file <- "ice_detentions_nov23-feb25.csv.gz"

df <- read_delim(here('analyze', 'input', file), delim='|') %>% 
  janitor::clean_names() %>% 
  mutate(stay_book_in_date_time = ymd_hms(stay_book_in_date_time),
         book_in_date_time = ymd_hms(book_in_date_time),
         detention_book_out_date_time = ymd_hms(detention_book_out_date_time),
         stay_book_out_date_time = ymd_hms(stay_book_out_date_time),
         )

```

```{r missingness}

sum(is.na(df$unique_identifier))
sum(is.na(df$stay_book_in_date_time))
sum(is.na(df$book_in_date_time))
sum(is.na(df$detention_book_out_date_time))
sum(is.na(df$stay_book_out_date_time))
sum(is.na(df$detention_facility))

```

```{r unique_ids}

length(unique(df$unique_identifier))

sum(is.na(df$unique_identifier))

```


```{r known_facilities}

known_facil <- read_delim(here::here('analyze', 'input', 'facilities.csv.gz'), delim ='|')

df <- df %>% 
  mutate(known_facil = detention_facility_code %in% unique(known_facil$detloc))

# Most detention records involve known facilities (NIJC 2017 + UWCHR)
sum(df$known_facil) / nrow(df)

# List of "new" facilities
unknown_facil <- unique(df[df$known_facil == FALSE, c("detention_facility_code", "detention_facility")]) %>% 
  arrange(detention_facility)

write_delim(unknown_facil, here::here('analyze', 'output', 'unknown_facilities_2025.csv'), delim=',')

to_join <- known_facil %>% 
  dplyr::select(detloc, aor, state, circuit, over_72, type) %>% 
  rename(detention_facility_code = detloc,
         detention_facility_aor = aor,
         detention_facility_state = state,
         detention_facility_circuit = circuit,
         detention_facility_over_72 = over_72,
         detention_facility_type = type)

df <- df %>% 
  left_join(to_join, by="detention_facility_code")

detloc_aor <- known_facil %>% 
  rename(detention_facility_code = detloc,
         area_of_responsibility = aor) %>% 
  distinct(detention_facility_code, area_of_responsibility) %>% 
  arrange(detention_facility_code, area_of_responsibility)

detloc_aor_list <- as.list(detloc_aor$detention_facility_code)

names(detloc_aor_list) <- detloc_aor$area_of_responsibility

df$first_aor <- names(detloc_aor_list)[match(df$first_facil, detloc_aor_list)]
df$last_aor <- names(detloc_aor_list)[match(df$last_facil, detloc_aor_list)]
df$prev_aor <- names(detloc_aor_list)[match(df$prev_facil, detloc_aor_list)]
df$longest_aor <- names(detloc_aor_list)[match(df$longest_placement_facil, detloc_aor_list)]

df <- df %>% 
  mutate(detention_facility_region = case_when(detention_facility_aor == "ATL" ~ "Interior/Northern",
          detention_facility_aor == "BAL" ~ "Interior/Northern",
          detention_facility_aor == "BOS" ~ "Interior/Northern",
          detention_facility_aor == "BUF" ~ "Interior/Northern",
          detention_facility_aor == "CHI" ~ "Interior/Northern",
          detention_facility_aor == "DAL" ~ "Interior/Northern",
          detention_facility_aor == "DEN" ~ "Interior/Northern",
          detention_facility_aor == "DET" ~ "Interior/Northern",
          detention_facility_aor == "ELP" ~ "Southern",
          detention_facility_aor == "HOU" ~ "Southern",
          detention_facility_aor == "LOS" ~ "Interior/Northern",
          detention_facility_aor == "MIA" ~ "Interior/Northern",
          detention_facility_aor == "NEW" ~ "Interior/Northern",
          detention_facility_aor == "NOL" ~ "Interior/Northern",
          detention_facility_aor == "NYC" ~ "Interior/Northern",
          detention_facility_aor == "PHI" ~ "Interior/Northern",
          detention_facility_aor == "PHO" ~ "Southern",
          detention_facility_aor == "SEA" ~ "Interior/Northern",
          detention_facility_aor == "SFR" ~ "Interior/Northern",
          detention_facility_aor == "SLC" ~ "Interior/Northern",
          detention_facility_aor == "SNA" ~ "Southern",
          detention_facility_aor == "SND" ~ "Southern",
          detention_facility_aor == "SPM" ~ "Interior/Northern",
          detention_facility_aor == "WAS" ~ "Interior/Northern"))

```

```{r vera_facilities}

vera_facil <- read_delim(here::here('analyze', 'frozen', 'vera_facilities.csv'), delim = ",")

vera_detlocs <- unique(vera_facil$detention_facility_code)
ddp_detlocs <- unique(df$detention_facility_code)
uwchr_detlocs <- unique(known_facil$detloc)
unk_facil <- unique(unknown_facil$detention_facility_code)

sets <- list("vera" = vera_detlocs,
             # "ddp" = ddp_detlocs,
             "uwchr" = uwchr_detlocs,
             "ddp_unknown" = unk_facil)

p2 <- ggVennDiagram(x = sets,
              force_upset = TRUE, order.set.by = "name", order.intersect.by = "size"
              )

p2 

```