---
title: "ICE ERO-LESA detention data Nov. 2023-Feb. 2025"
author: "UWCHR"
date: "2025-03-25"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, digest, ggsankeyfier)

file <- "ice_detentions_nov23-jun25.csv.gz"

df <- read_delim(here('analyze', 'input', file), delim='|') %>% 
  janitor::clean_names() %>% 
  mutate(stay_book_in_date_time = ymd_hms(stay_book_in_date_time),
         book_in_date_time = ymd_hms(book_in_date_time),
         detention_book_out_date_time = ymd_hms(detention_book_out_date_time),
         stay_book_out_date_time = ymd_hms(stay_book_out_date_time),
         )

```

```{r missingness}

sum(is.na(df$unique_identifier))
sum(is.na(df$stay_book_in_date_time))
sum(is.na(df$book_in_date_time))
sum(is.na(df$detention_book_out_date_time))
sum(is.na(df$stay_book_out_date_time))
sum(is.na(df$detention_facility))

```

```{r unique_ids}

length(unique(df$unique_identifier))

sum(is.na(df$unique_identifier))

```

```{r initial_placement_check}

sum(df$initial_placement_exact)
sum(df$initial_placement_approx)

first_reported_placement <- df %>% 
  filter(placement_count == 1)

p1 <- first_reported_placement %>% 
  mutate(book_in_year = year(stay_book_in_date_time)) %>% 
  count(book_in_year, initial_placement_exact) %>% 
  ggplot(aes(x = book_in_year, y = n, fill = initial_placement_exact)) +
  geom_col()

p1

first_reported_placement %>% 
  group_by(initial_placement_exact) %>% 
  summarize(mean(stay_length_elapsed))

```

```{r known_facilities}

known_facil <- read_delim(here::here('analyze', 'input', 'facilities.csv.gz'), delim ='|')

df <- df %>% 
  mutate(known_facil = detention_facility_code %in% unique(known_facil$detloc))

# Most detention records involve known facilities (NIJC 2017 + UWCHR)
sum(df$known_facil) / nrow(df)

# List of "new" facilities
unknown_facil <- unique(df[df$known_facil == FALSE, c("detention_facility_code", "detention_facility")]) %>% 
  arrange(detention_facility)

write_delim(unknown_facil, here::here('analyze', 'output', 'unknown_facilities_2025.csv'), delim=',')

to_join <- known_facil %>% 
  dplyr::select(detloc, aor, state, circuit, over_72, type) %>% 
  rename(detention_facility_code = detloc,
         detention_facility_aor = aor,
         detention_facility_state = state,
         detention_facility_circuit = circuit,
         detention_facility_over_72 = over_72,
         detention_facility_type = type)

df <- df %>% 
  left_join(to_join, by="detention_facility_code")

detloc_aor <- known_facil %>% 
  rename(detention_facility_code = detloc,
         area_of_responsibility = aor) %>% 
  distinct(detention_facility_code, area_of_responsibility) %>% 
  arrange(detention_facility_code, area_of_responsibility)

detloc_aor_list <- as.list(detloc_aor$detention_facility_code)

names(detloc_aor_list) <- detloc_aor$area_of_responsibility

df$first_aor <- names(detloc_aor_list)[match(df$first_facil, detloc_aor_list)]
df$last_aor <- names(detloc_aor_list)[match(df$last_facil, detloc_aor_list)]
df$prev_aor <- names(detloc_aor_list)[match(df$prev_facil, detloc_aor_list)]
df$longest_aor <- names(detloc_aor_list)[match(df$longest_placement_facil, detloc_aor_list)]

df <- df %>% 
  mutate(detention_facility_region = case_when(detention_facility_aor == "ATL" ~ "Interior/Northern",
          detention_facility_aor == "BAL" ~ "Interior/Northern",
          detention_facility_aor == "BOS" ~ "Interior/Northern",
          detention_facility_aor == "BUF" ~ "Interior/Northern",
          detention_facility_aor == "CHI" ~ "Interior/Northern",
          detention_facility_aor == "DAL" ~ "Interior/Northern",
          detention_facility_aor == "DEN" ~ "Interior/Northern",
          detention_facility_aor == "DET" ~ "Interior/Northern",
          detention_facility_aor == "ELP" ~ "Southern",
          detention_facility_aor == "HOU" ~ "Southern",
          detention_facility_aor == "LOS" ~ "Interior/Northern",
          detention_facility_aor == "MIA" ~ "Interior/Northern",
          detention_facility_aor == "NEW" ~ "Interior/Northern",
          detention_facility_aor == "NOL" ~ "Interior/Northern",
          detention_facility_aor == "NYC" ~ "Interior/Northern",
          detention_facility_aor == "PHI" ~ "Interior/Northern",
          detention_facility_aor == "PHO" ~ "Southern",
          detention_facility_aor == "SEA" ~ "Interior/Northern",
          detention_facility_aor == "SFR" ~ "Interior/Northern",
          detention_facility_aor == "SLC" ~ "Interior/Northern",
          detention_facility_aor == "SNA" ~ "Southern",
          detention_facility_aor == "SND" ~ "Southern",
          detention_facility_aor == "SPM" ~ "Interior/Northern",
          detention_facility_aor == "WAS" ~ "Interior/Northern"))

```

```{r bookins_by_aor_state}

bookins_aor <- df %>% 
  filter(placement_count == 1,
         initial_placement_exact == TRUE,
         stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(yearmon = as.yearmon(stay_book_in_date_time),
         week = floor_date(stay_book_in_date_time, "week", week_start = "Monday")) %>% 
  count(week, detention_facility_aor)

p1 <- bookins_aor %>% 
  filter(week != as_datetime("2025-02-17")) %>% 
  ggplot(aes(x = week, y = n, color = detention_facility_aor)) +
  geom_line() +
  # geom_vline(xintercept=as_datetime("2025-01-20"), linetype="dashed") +
  facet_wrap(~detention_facility_aor, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "ICE detention book-ins in interior surged post-inauguration...",
       subtitle = "ICE weekly detention book-ins by detention facility AOR")


p1

bookins_region <- df %>% 
  filter(placement_count == 1,
         stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(yearmon = as.yearmon(stay_book_in_date_time),
         week = floor_date(stay_book_in_date_time, "week", week_start = "Monday")) %>% 
  count(week, detention_facility_region)

p1.1 <- bookins_region %>% 
  filter(week != as_datetime("2025-02-17"),
         !is.na(detention_facility_region)) %>% 
  ggplot(aes(x = week, y = n, color = detention_facility_region)) +
  geom_line() +
  geom_vline(xintercept=as_datetime("2025-01-20"), linetype="dashed") +
  ylim(0,NA) +
  facet_wrap(~detention_facility_region) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "ICE detention book-ins in interior surged post-inauguration...",
       subtitle = "ICE weekly detention book-ins by detention facility AOR")


p1.1

bookins_natl <- df %>% 
  filter(placement_count == 1,
         stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(yearmon = as.yearmon(stay_book_in_date_time),
         week = floor_date(stay_book_in_date_time, "week", week_start = "Monday")) %>% 
  count(week)

p2 <- bookins_natl %>% 
  filter(week != as_datetime("2025-02-17")) %>% 
  ggplot(aes(x = week, y = n)) +
  geom_line() +
  geom_vline(xintercept=as_datetime("2025-01-20"), linetype="dashed") +
  ylim(0,NA) +
  labs(title = "...but remained mostly stable nationwide in initial weeks of Trump II",
       subtitle = "ICE weekly detention book-ins nationwide")


p2

# bookins_state <- df %>% 
#   filter(placement_count == 1,
#          book_in_date_time >= "2023-10-01"
#          ) %>% 
#   mutate(yearmon = as.yearmon(book_in_date_time),
#          week = floor_date(book_in_date_time, "week", week_start = "Monday")) %>% 
#   count(week, detention_facility_state)
# 
# p2 <- bookins_state %>% 
#   filter(week != as_datetime("2025-02-17")) %>% 
#   ggplot(aes(x = week, y = n, color = detention_facility_state)) +
#   geom_line()
# 
# p2

```

```{r pre_post_trump_change}

dat <- df %>% 
  filter(placement_count == 1,
         initial_placement_exact == TRUE,
         stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(week = floor_date(book_in_date_time, "week", week_start = "Monday"),
         trump = book_in_date_time >= "2025-01-20") %>% 
  group_by(trump, week, detention_facility_aor) %>% 
  count() %>% 
  group_by(trump, detention_facility_aor) %>% 
  summarize(weekly_mean_bookins = mean(n))

p1 <- dat %>% 
  ggplot(aes(x = detention_facility_aor, y = weekly_mean_bookins, fill = trump)) +
  geom_col(position='dodge')

p1

dat2 <- dat %>% 
  pivot_wider(id_cols='detention_facility_aor', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_bookins') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

p2 <- dat2 %>% 
  mutate(detention_facility_aor = fct_reorder(detention_facility_aor, pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = detention_facility_aor, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. initial bookins in first weeks of Trump II")

p2

```

```{r pre_post_trump_change_transfers}

dat <- df %>% 
  filter(placement_count > 1,
         stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(week = floor_date(book_in_date_time, "week", week_start = "Monday"),
         trump = book_in_date_time >= "2025-01-20") %>% 
  group_by(trump, week, detention_facility_aor) %>% 
  count() %>% 
  group_by(trump, detention_facility_aor) %>% 
  summarize(weekly_mean_bookins = mean(n))

p1 <- dat %>% 
  ggplot(aes(x = detention_facility_aor, y = weekly_mean_bookins, fill = trump)) +
  geom_col(position='dodge')

p1

dat2 <- dat %>% 
  pivot_wider(id_cols='detention_facility_aor', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_bookins') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

p2 <- dat2 %>% 
  mutate(detention_facility_aor = fct_reorder(detention_facility_aor, pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = detention_facility_aor, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. detention transfers in first weeks of Trump II")

p2

```

```{r pre_post_trump_change_facil_bookins}

dat <- df %>% 
  filter(placement_count == 1,
         initial_placement_exact == TRUE,
         stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(week = floor_date(book_in_date_time, "week", week_start = "Monday"),
         trump = book_in_date_time >= "2025-01-20") %>% 
  group_by(trump, week, detention_facility) %>% 
  count() %>% 
  group_by(trump, detention_facility) %>% 
  summarize(weekly_mean_bookins = mean(n))

# p1 <- dat %>% 
#   ggplot(aes(x = detention_facility_aor, y = weekly_mean_bookins, fill = trump)) +
#   geom_col(position='dodge')
# 
# p1

dat2 <- dat %>% 
  pivot_wider(id_cols='detention_facility', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_bookins') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

dat2 %>% 
  head(10)

dat2 %>% 
  filter(!is.na(pct_change)) %>% 
  tail(10)

```

```{r pre_post_trump_change_facil_transfers}

dat <- df %>% 
  filter(placement_count > 1,
         stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(week = floor_date(book_in_date_time, "week", week_start = "Monday"),
         trump = book_in_date_time >= "2025-01-20") %>% 
  group_by(trump, week, detention_facility) %>% 
  count() %>% 
  group_by(trump, detention_facility) %>% 
  summarize(weekly_mean_bookins = mean(n))

# p1 <- dat %>% 
#   ggplot(aes(x = detention_facility_aor, y = weekly_mean_bookins, fill = trump)) +
#   geom_col(position='dodge')
# 
# p1

dat2 <- dat %>% 
  pivot_wider(id_cols='detention_facility', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_bookins') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

dat2 %>% 
  head(10)

dat2 %>% 
  filter(!is.na(pct_change)) %>% 
  tail(10)

```


```{r pre_post_trump_change_circuit}

dat <- df %>% 
  filter(stay_book_in_date_time >= "2024-01-01"
         ) %>% 
  mutate(week = floor_date(book_in_date_time, "week", week_start = "Monday"),
         trump = book_in_date_time >= "2025-01-20") %>% 
  group_by(trump, week, detention_facility_circuit) %>% 
  count() %>% 
  group_by(trump, detention_facility_circuit) %>% 
  summarize(weekly_mean_bookins = mean(n))

p1 <- dat %>% 
  ggplot(aes(x = detention_facility_circuit, y = weekly_mean_bookins, fill = trump)) +
  geom_col(position='dodge')

p1

dat2 <- dat %>% 
  pivot_wider(id_cols='detention_facility_circuit', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_bookins') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

p2 <- dat2 %>% 
  mutate(detention_facility_circuit = fct_reorder(as.character(detention_facility_circuit), pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = detention_facility_circuit, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. detention bookins in first weeks of Trump II")

p2

```


```{r get_wa_arrests}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Admin_Arrests.xlsx"

arr <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

arr <- arr %>% 
  mutate(apprehension_date = as.Date(apprehension_date)) |>
  mutate(apprehension_method = fct(apprehension_method)) |>
  mutate(criminality = apprehension_criminality == "1 Convicted Criminal") |>
  mutate(n_dupe = row_number(), .by = c("unique_identifier")) |>
  filter(!is.na(unique_identifier))

arrest_ids <- unique(arr$unique_identifier)

to_join <- arr %>%
  dplyr::select(unique_identifier, apprehension_aor, apprehension_state)

to_join <- to_join[!duplicated(to_join$unique_identifier), ]

arr_ids <- arr$unique_identifier

df <- df %>% left_join(to_join, by='unique_identifier')

df <- df %>% 
  mutate(id_in_arr = unique_identifier %in% arr_ids)

rm(to_join)

wa_arr <- arr %>%
  filter(apprehension_state == "WASHINGTON")

wa_facil <- c("FDLHOLD",
"HAVMCWA",
"RICHOLD",
"SPOHOLD",
"STJMCWA",
"TACGHWA",
"WNTHOLD",
"ABRDNWA",
"ADAMSWA",
"BLHHOLD",
"BENTOWA",
"CHELAWA",
"CLJUVWA",
"CLARKWA",
"COWLIWA",
"COWJVWA",
"ECOLOWA",
"FERRYWA",
"FORKSWA",
"FRANKWA",
"GRANTWA",
"KINCOWA",
"KITTIWA",
"MARTIWA",
"MASONWA",
"WAMCNEI",
"CSCNWWA",
"OKANOWA",
"PENDOWA",
"RRFINWA",
"REGJCWA",
"BOPSET",
"SEAICDF",
"SEAHOLD",
"SPOKAWA",
"STEVEWA",
"SUNNYWA",
"THURSWA",
"WHICOWA",
"YIKIMWA",
"YAKHOLD")

```

```{r wa_detentions}

wa_det <- df %>%
  filter(unique_identifier %in% unlist(wa_arr$unique_identifier))

wa_det %>%
  count(detention_facility) %>%
  arrange(desc(n))

wa_det %>%
  count(first_facil) %>%
  arrange(desc(n))

```



```{r headcounter_setup, message=FALSE, warning=FALSE, include=TRUE}

# Transform data to "fill in" missing `detention_book_out_date_time` values
# in order to account for ongoing detention stays at time of release of data
max_date <- max(df$stay_book_out_date_time, na.rm=TRUE)

df <- df %>%
  mutate(detention_book_out_date_time_min = 
           case_when(is.na(detention_book_out_date_time) ~ max_date,
                     TRUE ~ detention_book_out_date_time))

# Define timeline for calculation of daily detained population
timeline_start <- min(df$stay_book_in_date_time, na.rm=TRUE)
timeline_end <- max(df$stay_book_out_date_time, na.rm=TRUE)
timeline <- seq(timeline_start, timeline_end, by='day')

# Function counts all in-range detention placement records in dataset `df` for a
# given `date` by a given grouping variable `var`
headcounter <- function(date, df, group_vars) {
  
  in_range <- df[df$book_in_date_time <= date & df$detention_book_out_date_time_min > date,]
  
  in_range %>% 
    group_by(across(all_of(group_vars))) %>% 
    summarize(n = n()) %>% 
    complete(fill = list(n = 0)) %>% 
    mutate(date=date)
  
  }

```

```{r facil_headcount}

# Generate limited sample dataset
temp_df <- df %>%
  filter(detention_facility_code == "CSCNWWA")

top <- temp_df %>%
  count(stay_release_reason) %>%
  arrange(desc(n)) %>%
  head(10)

# Apply function to timeline
example_headcount <- lapply(timeline, headcounter, df=temp_df, group_vars=c('stay_release_reason'))

# Transform output into data frame
example_headcount_data <- map_dfr(example_headcount, bind_rows)

# Plot headcount
p1 <- example_headcount_data %>%
  mutate(stay_release_reason =
           case_when(stay_release_reason %in% top$stay_release_reason ~ stay_release_reason,
                                         is.na(stay_release_reason) ~ NA,
                                         TRUE ~ "ALL OTHERS")) %>% 
  filter(date >= "2023-11-15") %>%
  ggplot(aes(x = date, y = n, color = stay_release_reason), group = stay_release_reason ) +
  geom_line() +
  labs(title = "Daily detained population by `stay_release_reason`",
       subtitle = "Northwest ICE Processing Center")

p1

```


```{r facil_headcount}

# Generate limited sample dataset
temp_df <- df %>%
  filter(detention_facility_code == "CSCNWWA",
         placement_count > 1)

# Apply function to timeline
example_headcount <- lapply(timeline, headcounter, df=temp_df, group_vars=c('prev_facil'))

# Transform output into data frame
example_headcount_data <- map_dfr(example_headcount, bind_rows) %>% 
  filter(date >= "2023-11-15") %>%
  mutate(week = floor_date(date, "week", week_start = "Monday")) %>% 
  group_by(week, prev_facil) %>% 
  summarize(adp = mean(n))

# Plot headcount
p1 <- example_headcount_data %>%
  
  ggplot(aes(x = week, y = adp, color = prev_facil), group = prev_facil ) +
  geom_line() +
  labs(title = "Weekly ADP population by `prev_facil`",
       subtitle = "Northwest ICE Processing Center")

plotly::ggplotly(p1)

```


```{r facil_headcount_citizenship}

# Generate limited sample dataset
temp_df <- df %>%
  filter(detention_facility_code == "CSCNWWA")

# Apply function to timeline
example_headcount <- lapply(timeline, headcounter, df=temp_df, group_vars=c('citizenship_country'))

top <- temp_df %>%
  filter(!is.na(citizenship_country)) %>%
  count(citizenship_country) %>%
  arrange(desc(n)) %>%
  head(10)

# Transform output into data frame
example_headcount_data <- map_dfr(example_headcount, bind_rows)

# Plot headcount
p1 <- example_headcount_data %>%
  mutate(citizenship_country = case_when(citizenship_country %in% top$citizenship_country ~ citizenship_country,
                                         is.na(citizenship_country) ~ NA,
                                         TRUE ~ "ALL OTHERS"),
         date = as.Date(date)) %>%
  group_by(citizenship_country, date) %>%
  summarize(n = sum(n)) %>%
  filter(date >= "2023-11-15") %>%
  ggplot(aes(x = date, y = n, color = citizenship_country), group = citizenship_country ) +
  geom_line() +
  labs(title = "Daily detained population by `citizenship_country`",
       subtitle = "Northwest ICE Processing Center")

p1

# Plot headcount
p2 <- example_headcount_data %>%
  mutate(date = as.Date(date)) %>%
  group_by(citizenship_country, date) %>%
  summarize(n = sum(n)) %>%
  filter(date >= "2023-11-15") %>%
  ggplot(aes(x = date, y = n, color = citizenship_country), group = citizenship_country ) +
  geom_line() +
  labs(title = "Daily detained population by `citizenship_country`",
       subtitle = "Northwest ICE Processing Center")

plotly::ggplotly(p2)


```

```{r detention_outcomes}

dat <- df %>% 
  filter(!is.na(stay_release_reason)) %>%
  mutate(unique_identifier = paste(unique_identifier, stay_count, sep = '-')) %>% 
  distinct(unique_identifier, .keep_all=TRUE) %>% 
  mutate(week = floor_date(book_in_date_time, "week", week_start = "Monday"),
         trump = book_in_date_time >= "2025-01-20") %>% 
  count(trump, week, stay_release_reason) %>% 
  group_by(trump, stay_release_reason) %>% 
  summarize(weekly_mean_releases = mean(n))

p1 <- dat %>% 
  ggplot(aes(y = stay_release_reason, x = weekly_mean_releases, fill = trump)) +
  geom_col(position='dodge')

p1

dat2 <- dat %>% 
  pivot_wider(id_cols='stay_release_reason', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_releases') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

p2 <- dat2 %>% 
  filter(!is.na(pct_change)) %>% 
  mutate(stay_release_reason = fct_reorder(as.character(stay_release_reason), pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = stay_release_reason, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. detention release in first weeks of Trump II")

p2

# What does it mean for a detention stay to end as "Transferred"?

```

```{r detention_outcomes}

dat <- df %>% 
  filter(!is.na(stay_release_reason)) %>% 
  mutate(week = floor_date(book_in_date_time, "week", week_start = "Monday"),
         trump = book_in_date_time >= "2025-01-20") %>% 
  count(trump, week, stay_release_reason) %>% 
  group_by(trump, stay_release_reason) %>% 
  summarize(weekly_mean_releases = mean(n))

p1 <- dat %>% 
  ggplot(aes(y = stay_release_reason, x = weekly_mean_releases, fill = trump)) +
  geom_col(position='dodge')

p1

dat2 <- dat %>% 
  pivot_wider(id_cols='stay_release_reason', names_from = "trump", names_prefix="trump_", values_from= 'weekly_mean_releases') %>% 
  mutate(pct_change = ((trump_TRUE - trump_FALSE) / trump_FALSE) * 100) %>% 
  arrange(desc(pct_change))

p2 <- dat2 %>% 
  filter(!is.na(pct_change)) %>% 
  mutate(stay_release_reason = fct_reorder(as.character(stay_release_reason), pct_change),
         pos = pct_change > 0) %>% 
  ggplot(aes(x = pct_change, y = stay_release_reason, fill = pos)) +
  geom_col(show.legend = FALSE) +
  labs(title = "% change in weekly avg. detention release in first months of Trump II")

p2

# What does it mean for a detention stay to end as "Transferred"?

```

```{r seahold}

dat <- df %>% 
  filter(detention_facility_code == "CSCNWWA",
         placement_count == total_placements)

temp <- dat %>%
  count(stay_release_reason) %>% 
  arrange(desc(n))

```

```{r wa_bookins}

wa_bookins <- df %>% 
  filter(detention_facility_code %in% wa_facil) %>% 
  mutate(week = floor_date(stay_book_in_date_time, "week", week_start = "Monday"),
         yearmon = as.yearmon(stay_book_in_date_time))

t1 <- wa_bookins %>% 
  filter(stay_book_in_date_time >= "2025-01-20") %>% 
  count(detention_facility)

p1 <- wa_bookins %>% 
  filter(stay_book_in_date_time >= "2023-11-01") %>% 
  count(yearmon, detention_facility) %>% 
  ggplot(aes(x = yearmon, y = n, fill = detention_facility)) +
  geom_col()

p1

p2 <- wa_bookins %>% 
  filter(stay_book_in_date_time >= "2025-01-01") %>% 
  count(week, detention_facility) %>% 
  ggplot(aes(x = week, y = n, fill = detention_facility)) +
  geom_col() +
  labs(title = "Weekly WA detention facil. book-ins",
       subtitle = "Since Jan. 2025")

p2

```


```{r natl_headcount_per_facil}

headcount_df <- read_delim(here::here('detain-headcount', 'output', 'headcount_detloc_nov23-jun25.csv.gz'), delim='|')

cscnwwa <- headcount_df %>% 
  filter(detention_facility_code == "CSCNWWA")

```

```{r 24_hr_headcounter_setup, message=FALSE, warning=FALSE, include=TRUE}

# This is intended to be a 24-hour inclusive population count, versus midnight headcount

# Transform data to "fill in" missing `detention_book_out_date_time` values
# in order to account for ongoing detention stays at time of release of data
max_date <- max(df$stay_book_out_date_time, na.rm=TRUE)

df <- df %>%
  mutate(detention_book_out_date_time_min = 
           case_when(is.na(detention_book_out_date_time) ~ max_date,
                     TRUE ~ detention_book_out_date_time))

# Define timeline for calculation of daily detained population
timeline_start <- date(min(df$stay_book_in_date_time, na.rm=TRUE))
timeline_end <- date(max(df$stay_book_out_date_time, na.rm=TRUE))
timeline <- seq(timeline_start, timeline_end, by='day')

# Function counts all in-range detention placement records in dataset `df` for a
# given `date` by a given grouping variable `var`
headcounter_24hr <- function(date, df, group_vars) {
  
  in_range <- df[date(df$book_in_date_time) <= date(date) & date(df$detention_book_out_date_time_min) > date(date),]
  
  in_range %>% 
    group_by(across(all_of(group_vars))) %>% 
    summarize(n = n()) %>% 
    complete(fill = list(n = 0)) %>% 
    mutate(date=date)
  
  }

```

```{r cscnwwa_24_hr_headcount}

# Generate limited sample dataset
temp_df <- df %>%
  filter(detention_facility_code == "CSCNWWA")

# Apply function to timeline
cscnwwa_24_hr <- lapply(timeline, headcounter_24hr, df=temp_df, group_vars=c('detention_facility_code'))


# Transform output into data frame
cscnwwa_24_hr <- map_dfr(cscnwwa_24_hr, bind_rows)

```

Is this right? Why would 24-hr inclusive headcount ever be lower than midnight headcount? Double check logics here and in headcount script

```{r compare_headcounts}

cscnwwa <- cscnwwa %>% 
  mutate(type = "headcount")

cscnwwa_24_hr <- cscnwwa_24_hr %>% 
  mutate(type = "24-hr")

dat <- rbind(cscnwwa, cscnwwa_24_hr)

dat_wide <- dat %>% 
  pivot_wider(id_cols = "date", names_from="type", values_from="n") %>% 
  mutate(diff = `24-hr` - headcount)

p1 <- dat %>% 
  ggplot(aes(x=date, y = n, color = type)) +
  geom_line()

p1

p2 <- dat_wide %>% 
  ggplot(aes(x = date , y=diff)) +
  geom_line()

p2

```

```{r geotrack}

geotrack <- read_delim(here::here('analyze', 'hand', 'cscnwwa_geo_track.csv'), delim='|') %>% 
  mutate(detention_facility_code = "CSCNWWA")

cscnwwa_2025 <- cscnwwa %>% 
  mutate(type = "headcount") %>% 
  filter(date >= "2025-01-01")

dat <- rbind(cscnwwa_2025, geotrack)

dat_wide <- dat %>% 
  pivot_wider(id_cols = "date", names_from="type", values_from="n") %>% 
  mutate(diff = geo_track - headcount,
         week = week(date),
         wday = wday(date))

p1 <- dat %>% 
  ggplot(aes(x=date, y = n, color = type)) +
  geom_line()

p1

p2 <- dat_wide %>% 
  ggplot(aes(x = date , y=diff)) +
  geom_line()

p2

p3 <- dat_wide %>% 
  filter(date < "2025-03-01") %>% 
  ggplot(aes(x = wday , y=diff, color = week)) +
  geom_line(aes(group = week))

p3

```