---
title: "Comparison of anonymized identifiers across datasets"
author: "UWCHR"
date: "2025-03-31"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, ggVennDiagram, UpSetR)

```


```{r setup_encounters, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Encounters.xlsx"

encounter_df1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>%
  janitor::clean_names()

encounter_df2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>%
  janitor::clean_names()

names_1 <- names(encounter_df1)
names_2 <- names(encounter_df2)

stopifnot(names_1 == names_2)

encounter_df <- rbind(encounter_df1, encounter_df2)

rm(encounter_df1, encounter_df2)

```


```{r setup_detainers}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Detainers.xlsx"

detainer_df<- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

```

```{r setup_arrests, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Admin_Arrests.xlsx"

arrest_df<- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

```

```{r setup_detention, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Detentions.xlsx"

detention_df1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>%
	janitor::clean_names()

detention_df2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>%
	janitor::clean_names()

names_1 <- names(detention_df1)
names_2 <- names(detention_df2)

stopifnot(names_1 == names_2)

detention_df <- rbind(detention_df1, detention_df2)

rm(detention_df1, detention_df2)


```

```{r setup_removals, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Removals_2025.xlsx"

removal_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

```

```{r compare_missingness_id}

data_levels <- c("encounter", "detainer", "arrest", "detention", "removal")

dat1 <- encounter_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "encounter")

dat2 <- detainer_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "detainer")

dat3 <- arrest_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "arrest")

dat4 <- detention_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "detention")

dat5 <- removal_df %>% 
  mutate(missing_id = is.na(unique_identifier)) %>% 
  count(missing_id) %>% 
  mutate(type = "removal")

dat <- rbind(dat1, dat2, dat3, dat4, dat5)

p1 <- dat %>% 
  mutate(type = factor(type, levels = data_levels)) %>% 
  ggplot(aes(x = type, y = n, fill = missing_id)) +
  geom_col()

p1

p1.1 <- dat %>% 
  mutate(type = factor(type, levels = data_levels)) %>% 
  ggplot(aes(x = type, y = n, fill = missing_id)) +
  geom_col(position="fill")

p1.1

```

```{r compare_sets}

encounter_df <- encounter_df %>% 
  filter(!is.na(unique_identifier))

detainer_df <- detainer_df %>% 
  filter(!is.na(unique_identifier))

arrest_df <- arrest_df %>% 
  filter(!is.na(unique_identifier))

detention_df <- detention_df %>% 
  filter(!is.na(unique_identifier))

removal_df <- removal_df %>% 
  filter(!is.na(unique_identifier))

encounter_ids <- unique(encounter_df$unique_identifier)
detainer_ids <- unique(detainer_df$unique_identifier)
arrest_ids <- unique(arrest_df$unique_identifier)
detention_ids <- unique(detention_df$unique_identifier)
removal_ids <- unique(removal_df$unique_identifier)

sets <- list("encounters" = encounter_ids,
             "detainers" = detainer_ids,
             "arrests" = arrest_ids,
             "detentions" = detention_ids,
             "removals" = removal_ids)

p1 <- ggVennDiagram(x = sets,
              force_upset = TRUE, order.set.by = "name", order.intersect.by = "size"
              )

p1

```
