---
title: "Lookup and summary of individual case records across datasets"
author: "UWCHR"
date: "2025-07-03"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

Note `unique_identifier` values will change for each successive installment.

```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, ggforce, plotly, gghighlight, viridis, readxl, ggVennDiagram)

```

```{r setup_encounters, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Encounters.xlsx"

encounter_df_1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>%
  janitor::clean_names() %>%
  mutate(event_date = as.Date(event_date))

encounter_df_2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>%
  janitor::clean_names() %>%
  mutate(event_date = as.Date(event_date))

encounter_df <- rbind(encounter_df_1, encounter_df_2)

rm(encounter_df_1, encounter_df_2)

encounter_ids <- unique(encounter_df$unique_identifier)

```


```{r setup_detainers}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Detainers.xlsx"

detainer_df<- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

detainer_df<- detainer_df%>% 
  mutate(date_diff = difftime(detainer_prepare_date, apprehension_date, units = "days"))

detainer_ids <- unique(detainer_df$unique_identifier)

```

```{r setup_arrests, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Admin_Arrests.xlsx"

arrest_df<- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

arrest_df <- arrest_df %>% 
  mutate(apprehension_date = as.Date(apprehension_date)) |>
  mutate(apprehension_method = fct(apprehension_method)) |>
  mutate(criminality = apprehension_criminality == "1 Convicted Criminal") |>
  mutate(n_dupe = row_number(), .by = c("unique_identifier")) |>
  filter(!is.na(unique_identifier))

arrest_ids <- unique(arrest_df$unique_identifier)

```

```{r setup_detention, message=FALSE, warning=FALSE, include=TRUE}

file <- "ice_detentions_nov23-jun25.csv.gz"

detention_df <- read_delim(here('analyze', 'input', file), delim='|') %>% 
  mutate(stay_book_in_date_time = ymd_hms(stay_book_in_date_time),
         book_in_date_time = ymd_hms(book_in_date_time),
         detention_book_out_date_time = ymd_hms(detention_book_out_date_time),
         stay_book_out_date_time = ymd_hms(stay_book_out_date_time),
         stay_book_out_date = ymd(stay_book_out_date),
         book_in_fy = substr(quarter(book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4),
         stay_book_in_fy = substr(quarter(stay_book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4)) %>% filter(!is.na(unique_identifier))


detention_df <- detention_df %>% 
  group_by(unique_identifier) %>% 
  arrange(stay_book_in_date_time, book_in_date_time, unique_identifier) %>% 
  ungroup()

detention_ids <- unique(detention_df$unique_identifier)

```

```{r setup_removals, message=FALSE, warning=FALSE, include=TRUE}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Removals_2025.xlsx"

removal_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names() %>% filter(!is.na(unique_identifier))

removal_ids <- unique(removal_df$unique_identifier)

```

Tuan Phan: 2b523cdad2a0705f5f06c4a1860c606e439c8abe (Jun) a368928348a2bf82b7c3f9377d66e41002cb762d (Jul)

```{r}

id_lookup <- function(unique_identifier, dataset, output = FALSE) {
  
  records <- dataset[dataset$unique_identifier == unique_identifier,]
  
  if (output == "kable" | output == TRUE) {
    knitr::kable(records)
  } else if (output == "df" | output == FALSE) {
    records
  } else if (output == "text") {
      for (n in seq(nrow(records))) {
        for (i in seq(length(records[n,]))) {
          print(paste(names(records[n,i]), ": ", records[n,i]))
        }
      }
    }
  }

```

```{r}

id_lookup("b970c968ba8babd9b92ff3fd739fe30232666d59", arrest_df, output="text")

```

```{r}

id_lookup("b970c968ba8babd9b92ff3fd739fe30232666d59", encounter_df, output=FALSE)

```

```{r}

datasets <- c(encounter_df, detainer_df, arrest_df, detention_df, removal_df)

lookup_all <- function(lookup_id, datasets) {
  
  records <- id_lookup(lookup_id, encounter_df)
  
  # for (n in 1:length(datasets)) {
  #   print(id_lookup(unique_identifier, dataset[n]))
  # }
  
}

temp <- lookup_all("2b523cdad2a0705f5f06c4a1860c606e439c8abe", datasets)

```

```{r shared_cols}

encounter_cols <- names(encounter_df)
detainer_cols <- names(detainer_df)
arrest_cols <- names(arrest_df)
detention_cols <- names(detention_df)
removal_cols <- names(removal_df)

shared_cols <- Reduce(intersect, list(encounter_cols, detainer_cols, arrest_cols, detention_cols, removal_cols))

```

```{r long_record}

lookup_enforcement <- function(id_to_search) {

  encounter_recs <- encounter_df %>% 
    mutate(date = as_datetime(event_date),
           aor = responsible_aor,
           loc = responsible_site) %>% 
    filter(unique_identifier == id_to_search) %>% 
    mutate(type = "encounter") %>% 
    dplyr::select(unique_identifier, type, date, aor, loc, shared_cols)
  
  detainer_recs <- detainer_df %>% 
    mutate(date = as_datetime(detainer_prepare_date),
           aor = facility_aor,
           loc = detention_facility) %>% 
    filter(unique_identifier == id_to_search) %>% 
    mutate(type = "detainer") %>% 
    dplyr::select(unique_identifier, type, date, aor, loc, shared_cols)
  
  arrest_recs <- arrest_df %>% 
    mutate(date = as_datetime(apprehension_date),
           aor = apprehension_aor,
           loc = apprehension_state) %>% 
    filter(unique_identifier == id_to_search) %>% 
    mutate(type = "arrest") %>% 
    dplyr::select(unique_identifier, type, date, aor, loc, shared_cols)
  
  detention_book_in_recs <- detention_df %>% 
    mutate(date = as_datetime(book_in_date_time),
           aor = "",
           loc = detention_facility) %>% 
    filter(unique_identifier == id_to_search) %>% 
    mutate(type = "detention book-in") %>% 
    dplyr::select(unique_identifier, type, date, aor, loc, shared_cols)
  
  detention_book_out_recs <- detention_df %>% 
    mutate(date = as_datetime(detention_book_out_date_time),
           aor = "",
           loc = detention_facility) %>% 
    filter(unique_identifier == id_to_search) %>% 
    mutate(type = "detention book-out") %>% 
    dplyr::select(unique_identifier, type, date, aor, loc, shared_cols)
  
  detention_recs <- rbind(detention_book_in_recs, detention_book_out_recs) %>% 
    arrange(date)
  
  removal_recs <- removal_df %>% 
    mutate(date = as_datetime(departed_date),
           aor = docket_aor,
           loc = port_of_departure) %>% 
    filter(unique_identifier == id_to_search) %>% 
    mutate(type = "removal") %>% 
    dplyr::select(unique_identifier, type, date, aor, loc, shared_cols)
  
  enforce_history <- rbind(encounter_recs,
                           detainer_recs,
                           arrest_recs,
                           detention_recs,
                           removal_recs)

  return(enforce_history)

  }

```

```{r}

gitmo_1 <- lookup_enforcement("32ecf71f8c5c1317db065c56ccb0799726210e10")
gitmo_2 <- lookup_enforcement("404ddf03e7dbc57a5e0358fa289e5ddc57c28ec8")
gitmo_3 <- lookup_enforcement("b5b6f878e614b5051994b19ae62442285d8e5141")
gitmo_4 <- lookup_enforcement("7ac85e0070dc9867e573f87a917e9f45f79abe68")
gitmo_5 <- lookup_enforcement("c4fb041921bf0add3a8e4ac7316042eae45ba96c")

temp <- rbind(gitmo_1, gitmo_2, gitmo_3, gitmo_4, gitmo_5)

write_delim(temp, here::here('analyze', 'output', 'draft_enforcement_history.csv'), delim=',', na="")

```

```{r lookup_bio}



```

```{r}

cecot_1 <- lookup_enforcement("a58058e5074ce32587c485e5aebabd08087d75af")
cecot_2 <- lookup_enforcement("b21ab06c15751a4a13a8ce8a680015bf60442b06")
cecot_3 <- lookup_enforcement("632599f913e5479629111c387f23392d13fbe0d6")
cecot_4 <- lookup_enforcement("cdde407ea67258920360f12d78b5c6e6c5335421")
cecot_5 <- lookup_enforcement("bce92d889ca807e8789d54e2785cde197f02cc43")
cecot_6 <- lookup_enforcement("129045ad3aa54bc7a1d75f0eb10fbe46c8655ce1")

temp <- rbind(cecot_1, cecot_2, cecot_3, cecot_4, cecot_5, cecot_6)

write_delim(temp, here::here('analyze', 'output', 'cecot_enforcement_histories.csv'), delim=',', na="")

```

```{r}

mar_8_rem_1 <- lookup_enforcement("4f3c482c06c80c256789c00c4ce089170dec9fcc")
mar_8_rem_2 <- lookup_enforcement("843819825de5ddc381c477977847a80a0548b6d2")
mar_8_rem_3 <- lookup_enforcement("936fde6b9a188c7de19f2b194af416a14bb31226")
mar_8_rem_4 <- lookup_enforcement("b6a396b46845aa245798cebc167a42f92974c5ae")
mar_8_rem_5 <- lookup_enforcement("c48fd5c0164df37ad88b11b1faded8051c553d42")
mar_8_rem_6 <- lookup_enforcement("c556d4761f607283e29278350de36e5b6f41d437")
mar_8_rem_7 <- lookup_enforcement("cc0250354d89105482b537832524d94dce59ef96")
mar_8_rem_8 <- lookup_enforcement("ce445ea17043d89acf655c5f593f2e35c41df5f7")

march8_removals_lookup <- rbind(mar_8_rem_1, mar_8_rem_2, mar_8_rem_3, mar_8_rem_4, mar_8_rem_5, mar_8_rem_6, mar_8_rem_7, mar_8_rem_8)

write_delim(march8_removals_lookup, here::here('analyze', 'output', 'mar_8_removals_enforcement_histories.csv'), delim=',', na="")

```
