---
title: "Non-Detained Docket Control/Non-Custodial Arrest Pathway Analysis"
author: "UWCHR"
date: "2025-06-07"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, ggVennDiagram)

```

```{r setup_facilities, message=FALSE, warning=FALSE, include=TRUE}

# Running into problem with .gz version of facilities dataset
file <- "facilities.csv"

facilities_df <- read_delim(here('analyze', 'input', file), delim='|') %>% 
  janitor::clean_names()

```

```{r setup_detainers, message=FALSE, warning=FALSE, include=TRUE}

file <- "ERO_Detainers_2025-ICLI-00019_2024-ICFO-39357_LESA-STU_FINAL_raw.xlsx"

detainer_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(date_diff = difftime(detainer_prepare_date, apprehension_date, units='days'),
         pre_trump = detainer_prepare_date < as.Date("2025-01-20"))

detainer_ids <- unique(detainer_df$unique_identifier)

```

```{r setup_encounters, message=FALSE, warning=FALSE, include=TRUE}

file <- "ERO_Encounters_2025-ICLI-00019_2024-ICFO-39357_LESA-STU_FINAL_raw.xlsx"

encounter_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(event_date = as.Date(event_date),
         pre_trump = event_date < as.Date("2025-01-20"))

encounter_ids <- unique(encounter_df$unique_identifier)

```

```{r setup_arrests, message=FALSE, warning=FALSE, include=TRUE}

file <- "ERO_Admin_Arrests_2025-ICLI-00019_2024-ICFO-39357_LESA-STU_FINAL_raw.xlsx"

arrest_df<- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(apprehension_date = as.Date(apprehension_date),
         apprehension_method = fct(apprehension_method),
         criminality = apprehension_criminality == "1 Convicted Criminal",
         n_dupe = row_number(), .by = c("apprehension_date", "apprehension_method", "apprehension_criminality", "unique_identifier"),
         pre_trump = apprehension_date < as.Date("2025-01-20")) %>% 
  filter(is.na(unique_identifier) | n_dupe == 1)

arrest_ids <- unique(arrest_df$unique_identifier)

```

```{r setup_detentions, message=FALSE, warning=FALSE, include=TRUE}

file <- "ice_detentions_nov23-feb25.csv.gz"

detain_unique_stays_df <- read_delim(here('analyze', 'input', file), delim='|') %>% 
  janitor::clean_names() %>% 
  mutate(stay_book_in_date_time = ymd_hms(stay_book_in_date_time),
         book_in_date_time = ymd_hms(book_in_date_time),
         detention_book_out_date_time = ymd_hms(detention_book_out_date_time),
         stay_book_out_date_time = ymd_hms(stay_book_out_date_time),
         pre_trump = stay_book_in_date_time < as.Date("2025-01-20")) %>% 
  left_join(facilities_df, by=c("detention_facility_code" = "detloc"))

```

```{r}
# Break down datasets by geography and pre vs. post Trump
segment_df <- function(df, unique_fn, geo_filter) {
  df_uq <- unique_fn(df)
  df_wa_uq <- unique_fn(geo_filter(df))
  df_pre_trump_uq <- unique_fn(filter(df, pre_trump == TRUE))
  df_post_trump_uq <- unique_fn(filter(df, pre_trump == FALSE))
  df_pre_trump_wa_uq <- unique_fn(geo_filter(filter(df, pre_trump == TRUE)))
  df_post_trump_wa_uq <- unique_fn(geo_filter(filter(df, pre_trump == FALSE)))
  
  return (list("uq"=df_uq,
            "wa_uq"=df_wa_uq,
            "pre_trump_uq"=df_pre_trump_uq,
            "post_trump_uq"=df_post_trump_uq,
            "pre_trump_wa_uq"=df_pre_trump_wa_uq,
            "post_trump_wa_uq"=df_post_trump_wa_uq))
}

detention_dfs <- segment_df(detain_unique_stays_df,
                           (function(df) return(df %>% filter(last_placement == TRUE))),
                           (function(df) return(df %>% filter(state == "WA"))))

encounter_dfs <- segment_df(encounter_df,
                           (function(df) return(df %>% arrange(desc(event_date)) %>% distinct(unique_identifier, .keep_all=TRUE))),
                           (function(df) return(df %>% filter(responsible_aor == "Seattle Area of Responsibility"))))

arrest_dfs <- segment_df(arrest_df,
                        (function(df) return(df %>% arrange(desc(apprehension_date)) %>% distinct(unique_identifier, .keep_all=TRUE))),
                        (function(df) return(df %>% filter(apprehension_aor == "Seattle Area of Responsibility"))))
```


```{r}
# Convert decimal to percentage
percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}
```

How many records of people going from "non-detained docket control" to "non-custodial arrest" also have detention records pre vs. post Trump?

```{r}
analyze_detention_records <- function(df1, df2) {
  joined_df <- df1 %>% 
    left_join(df2,
              by="unique_identifier",
              na_matches='never') %>% 
    filter(event_type == "Non-Detained Docket Control" &
           apprehension_method == "Non-Custodial Arrest") %>% 
    mutate(detention_record = unique_identifier %in% detention_ids)  
  
  df_count <- joined_df %>% 
  count(detention_record, name="count", sort=TRUE) %>% 
  mutate(pct = percent(count / nrow(joined_df))) %>% 
  arrange(desc(detention_record))
  
  print(df_count)
  return(df_count)
}
```

# By Arrests
```{r}
analyze_detention_records(arrest_dfs[["pre_trump_uq"]] %>% filter(apprehension_date >= as.Date("2024-11-20")), encounter_dfs[["pre_trump_uq"]])
analyze_detention_records(arrest_dfs[["post_trump_uq"]], encounter_dfs[["uq"]])
```

# By Encounters
```{r}
analyze_detention_records(encounter_dfs[["pre_trump_uq"]] %>% filter(event_date >= as.Date("2024-11-20")), arrest_dfs[["pre_trump_uq"]])
analyze_detention_records(encounter_dfs[["post_trump_uq"]], arrest_dfs[["uq"]])
```

# By Arrests (Seattle AOR)
```{r}
analyze_detention_records(arrest_dfs[["pre_trump_wa_uq"]] %>% filter(apprehension_date >= as.Date("2024-11-20")), encounter_dfs[["pre_trump_uq"]])
analyze_detention_records(arrest_dfs[["post_trump_wa_uq"]], encounter_dfs[["uq"]])
```

# By Encounters (Seattle AOR)
```{r}
analyze_detention_records(encounter_dfs[["pre_trump_wa_uq"]] %>% filter(event_date >= as.Date("2024-11-20")), arrest_dfs[["pre_trump_uq"]])
analyze_detention_records(encounter_dfs[["post_trump_wa_uq"]], arrest_dfs[["uq"]])
```

# Mean Detainer-Arrest Lag
```{r}
# Average time difference between book in date time and apprehension date
detention_arrest_df <- arrest_dfs[["uq"]] %>% 
  inner_join(detention_dfs[["uq"]],
       by="unique_identifier",
       na_matches='never') %>% 
  mutate(date_diff = difftime(book_in_date_time, apprehension_date, units='days'))

print(mean(detention_arrest_df$date_diff))
```

