---
title: "Comparison of anonymized identifiers across datasets"
author: "UWCHR"
date: "2025-03-31"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

- Venezuelans deported to El Salvador in March
	- that were arrested in SEA
	- that were detained at CSCNWWA

- Third country removals
	- of people arrested in SEA
	- of people detained at CSCNWWA
	- from SEA directly

- Trends
	- Case category codes
	- Nationality
	- transfers

```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, ggVennDiagram)

```

```{r setup_detainers}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Detainers_LESA-STU_FINAL_unprotected.xlsx"

detainer_df<- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

detainer_df<- detainer_df%>% 
  mutate(date_diff = difftime(detainer_prepare_date, apprehension_date, units = "days"))

detainer_ids <- unique(detainer_df$unique_identifier)

```

```{r setup_encounters}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Encounters_FINAL_unprotected.xlsx"

encounter_df_1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(event_date = as.Date(event_date))

encounter_df_2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(event_date = as.Date(event_date))

encounter_df <- rbind(encounter_df_1, encounter_df_2)

rm(encounter_df_1, encounter_df_2)

encounter_ids <- unique(encounter_df$unique_identifier)

```

```{r setup_arrests}

file <- "2025-ICLI-00019_2024-ICFO-39357_ERO_Admin_Arrests_LESA-STU_FINAL_unprotected.xlsx"

arrest_df<- read_excel(here('analyze', 'input', file), skip=5) %>% 
  janitor::clean_names()

arrest_df <- arrest_df %>% 
  mutate(apprehension_date = as.Date(apprehension_date)) |>
  mutate(apprehension_method = fct(apprehension_method)) |>
  mutate(criminality = apprehension_criminality == "1 Convicted Criminal") |>
  mutate(n_dupe = row_number(), .by = c("apprehension_date", "apprehension_method", "apprehension_criminality", "unique_identifier")) |>
  filter(is.na(unique_identifier) | n_dupe == 1)

arrest_ids <- unique(arrest_df$unique_identifier)

```

```{r setup_detention}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE_Detentions_LESA-STU_FINAL_unprotected.xlsx"

detention_df_1 <- read_excel(here('analyze', 'input', file), sheet=1, skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(stay_book_in_date_time = as.Date(stay_book_in_date_time, format = "%m/%d/%Y %H:%M"),
         book_in_date_time = as.Date(book_in_date_time, format = "%m/%d/%Y %H:%M"),
         stay_book_out_date_time = as.Date(stay_book_out_date_time, format = "%m/%d/%Y %H:%M"),
         stay_book_in_date_time = as.Date(stay_book_out_date, format = "%m/%d/%Y %H:%M"),
         book_in_fy = substr(quarter(book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4),
         stay_book_in_fy = substr(quarter(stay_book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4))

detention_df_2 <- read_excel(here('analyze', 'input', file), sheet=2, skip=6) %>% 
  janitor::clean_names() %>% 
  mutate(stay_book_in_date_time = as.Date(stay_book_in_date_time, format = "%m/%d/%Y %H:%M"),
         book_in_date_time = as.Date(book_in_date_time, format = "%m/%d/%Y %H:%M"),
         stay_book_out_date_time = as.Date(stay_book_out_date_time, format = "%m/%d/%Y %H:%M"),
         stay_book_in_date_time = as.Date(stay_book_out_date, format = "%m/%d/%Y %H:%M"),
         book_in_fy = substr(quarter(book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4),
         stay_book_in_fy = substr(quarter(stay_book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4))

detention_df <- rbind(detention_df_1, detention_df_2)

rm(detention_df_1, detention_df_2)

detention_ids <- unique(detention_df$unique_identifier)

```

```{r setup_removals}

file <- "2025-ICLI-00019_2024-ICFO-39357_ICE Removals_LESA-STU_FINAL_2025only_unprotected.xlsx"

removals_df <- read_excel(here('analyze', 'input', file), skip=6) %>% 
  janitor::clean_names()

removal_ids <- unique(removals_df$unique_identifier)

```

```{r compare_sets}

sets <- list("encounters" = encounter_ids,
             "detainers" = detainer_ids,
             "arrests" = arrest_ids,
             "detentions" = detention_ids,
             "removals" = removal_ids)

# p1 <- ggVennDiagram(x = sets,
#                     color = name,
#                     label = "count") +
#   scale_fill_gradient(low = "#F4FAFE", high = "#4981BF")
# 
# p1

p2 <- ggVennDiagram(x = sets,
              force_upset = TRUE, order.set.by = "name", order.intersect.by = "size"
              )

p2 

```

```{r setup_id_intersect_cols}

detention_df <- detention_df |>
  mutate(id_in_arrests = unique_identifier %in% arrest_ids,
         id_in_detainers = unique_identifier %in% detainer_ids)

arrest_df<- arrest_df|>
  mutate(id_in_detentions = unique_identifier %in% detention_ids,
         id_in_detainers = unique_identifier %in% detainer_ids)

detainer_df<- detainer_df|>
  mutate(id_in_arrests = unique_identifier %in% arrest_ids,
         id_in_detainers = unique_identifier %in% detainer_ids)

```

```{r}

dat <- detention_df %>% 
  mutate(fy = substr(quarter(book_in_date_time, fiscal_start = 10, type = "year.quarter"), 1, 4)) %>% 
  group_by(fy) %>% 
  summarize(id_in_arrests_mean = mean(id_in_arrests))

dat

```