---
title: "ICE ERO-LESA detention data Oct. 2022 - Mar. 2026"
author: "UWCHR"
date: "2026-04-01"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---


```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, digest, ggsankeyfier)

arrests <- arrow::read_parquet("https://github.com/deportationdata/ice/raw/refs/heads/main/data/arrests-latest.parquet")

# detentions <- arrow::read_parquet("https://github.com/deportationdata/ice/raw/refs/heads/main/data/detention-stints-latest.parquet")

stays <- arrow::read_parquet("https://github.com/deportationdata/ice/raw/refs/heads/main/data/detention-stays-latest.parquet")

# headcount <- arrow::read_parquet("https://github.com/deportationdata/ice/raw/refs/heads/main/data/facilities-daily-population-latest.parquet")

pnw_facil <- c("FDLHOLD",
"HAVMCWA",
"RICHOLD",
"SPOHOLD",
"STJMCWA",
"TACGHWA",
"WNTHOLD",
"ABRDNWA",
"ADAMSWA",
"BLHHOLD",
"BENTOWA",
"CHELAWA",
"CLJUVWA",
"CLARKWA",
"COWLIWA",
"COWJVWA",
"ECOLOWA",
"FERRYWA",
"FORKSWA",
"FRANKWA",
"GRANTWA",
"KINCOWA",
"KITTIWA",
"MARTIWA",
"MASONWA",
"WAMCNEI",
"CSCNWWA",
"OKANOWA",
"PENDOWA",
"RRFINWA",
"REGJCWA",
"BOPSET",
"SEAICDF",
"SEAHOLD",
"SPOKAWA",
"STEVEWA",
"SUNNYWA",
"THURSWA",
"WHICOWA",
"YIKIMWA",
"YAKHOLD",
"MEDHOLD",
"POOHOLD",
"EUGHOLD")

gtmo <- c("GTMOBCU",
"GTMODCU",
"GTMOACU")

big_new <-
      c(
        "EROFCB", # Camp East Montana
        "EPSSFTX", # El Paso soft-sided
        "FLDSSFS", # Florida soft-sided / alligator alcatraz
        "GTMOBCU", # Guantanamo
        "GTMODCU", # Guantanamo
        "GTMOACU", # Guantanamo
        "INMIAMI", # Speedway slammer
        "NEMCCOI", # Cornhusker clink
        "LICEPLA", # Angola / camp 57
        "DHDFNJ", # Delaney Hall
        "CACTYCA", # California City Corrections  - reopened by CoreCivic in 2025
        "IRWINGA", # Irwin County - reopened by LaSalle Corrections in 2025
        "NRLKCMI", # North Lake Processing Faciliy - reopened by Geo in 2025
        "FIPCAGA", # Folkston annex - opened by Geo in 2025
        "OKCIMMC", # Cimarron - CoreCivic 2025
        "OKDBACK", # Diamondback - CoreCivic 2026
        "STFRCTX", # Dilley
        "FLBAKCI" # Baker Correctional Institution - reopened in 2025
      )

```

```{r}

stays <- stays %>% 
  mutate(stays_inc_cscnwwa = str_detect(detention_facility_codes_all, "CSCNWWA"),
         stays_inc_erofcb = str_detect(detention_facility_codes_all, "EROFCB"),
         stays_inc_pnw_facil = str_detect(detention_facility_codes_all, paste(pnw_facil, collapse="|")),
         stays_inc_gtmo = str_detect(detention_facility_codes_all, paste(gtmo, collapse="|")),
         stays_inc_fldssfs = str_detect(detention_facility_codes_all, "FLDSSFS"),
         stays_inc_big_new = str_detect(detention_facility_codes_all, paste(big_new, collapse="|")),
         ice_arrest = unique_identifier %in% arrests$unique_identifier,
         sea_bookin = detention_facility_code_first %in% pnw_facil)

```

`book_in_aor` and `book_in_site` aren't simply AOR of first detention facility

```{r}

cscnwwa_stays <- stays %>% d
  filter(stays_inc_cscnwwa == TRUE)

dat <- cscnwwa_stays %>% 
  count(book_in_aor, stays_inc_erofcb)

p1 <- dat %>% 
  ggplot(aes(x = stays_inc_erofcb, y = n, fill = book_in_aor)) +
  geom_col(position="fill")

ggplotly(p1)

pnw_stays <- stays %>% 
  filter(detention_facility_code_first %in% pnw_facil)

dat1 <- pnw_stays %>% 
  count(book_in_aor, ice_arrest)

dat2 <- pnw_stays %>% 
  count(detention_facility_code_first, book_in_site)

```

```{r}

cscnwwa_stays <- stays %>% 
  filter(stays_inc_cscnwwa == TRUE)

dat <- cscnwwa_stays %>% 
  count(stay_release_reason, stays_inc_erofcb)

p1 <- dat %>% 
  ggplot(aes(x = stays_inc_erofcb, y = n, fill = stay_release_reason)) +
  geom_col(position="fill")

ggplotly(p1)

```


```{r}

cscnwwa_stays <- stays %>% 
  filter(stays_inc_cscnwwa == TRUE)

dat <- cscnwwa_stays %>% 
  count(citizenship_country, stays_inc_erofcb)

p1 <- dat %>% 
  ggplot(aes(x = stays_inc_erofcb, y = n, fill = citizenship_country)) +
  geom_col(position="fill")

ggplotly(p1)

```

```{r}

cscnwwa_stays <- stays %>% 
  filter(stays_inc_cscnwwa == TRUE)

sea_bookins <- stays %>% 
  filter(sea_bookin == TRUE)

sea_big_new <- sea_bookins[sea_bookins$stays_inc_big_new == TRUE,]



```

```{r}

sea_arrests_by_crim <- arrests %>% 
  filter(!duplicate_likely,
         !is.na(unique_identifier),
         !is.na(case_criminality),
         apprehension_date >= "2024-07-01",
         apprehension_aor == "Seattle Area of Responsibility") %>% 
  mutate(month = floor_date(apprehension_date, unit = "months")) %>% 
  count(month, case_criminality)

write_delim(sea_arrests_by_crim, "sea_arrests_by_case_criminality.csv", delim=",")

sea_bookins_by_msc_charge <- stays %>% 
  filter(detention_facility_code_first %in% pnw_facil,
         book_in_date_time_first >= "2025-10-01") %>% 
  count(msc_charge)

write_delim(sea_bookins_by_msc_charge, "sea_bookins_by_msc_charge.csv", delim=",")

```
